#!/usr/bin/env python3
"""Emit a handful of built-in pets as C arrays for the preview harness.

Lets the preview render the Usage page against varied avatar shapes, so
backdrop and silhouette-knockout changes can be checked against more than
the bundled pet.

Usage:
  tools/preview/gen_pet_samples.py            # writes tools/preview/out/pet_samples.h
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pet import PET_BYTES, load_pet_bits

OUT = Path(__file__).resolve().parent / "out" / "pet_samples.h"

SAMPLES = ("dewey", "fireball", "rocky", "bsod")


def main() -> int:
    entries = []
    for want in SAMPLES:
        label, bits = load_pet_bits(want)
        if len(bits) != PET_BYTES:
            raise SystemExit(f"{label}: expected {PET_BYTES} bytes, got {len(bits)}")
        body = ", ".join(f"0x{b:02X}" for b in bits)
        entries.append(f'  {{"{label}", {{{body}}}}},')
        print(f"converted {label}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Auto-generated by tools/preview/gen_pet_samples.py — do not edit.\n"
        "#pragma once\n\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "struct PetSample {\n"
        "  const char* name;\n"
        f"  uint8_t bits[{PET_BYTES}];\n"
        "};\n\n"
        "static const PetSample kPetSamples[] = {\n"
        + "\n".join(entries)
        + f"\n}};\nstatic const size_t kPetSampleCount = {len(entries)};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
