#!/usr/bin/env bash
# Fetch the Mozilla CA bundle (via curl.se) and embed it as a C header so the
# firmware can verify HTTPS without runtime downloads. Never ship insecure TLS.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/firmware/ca_bundle.h"
TMP="$(mktemp)"

curl -fsSL --proto '=https' --tlsv1.2 https://curl.se/ca/cacert.pem -o "$TMP"

{
  echo "// Auto-generated by tools/gen_ca_bundle.sh from https://curl.se/ca/cacert.pem"
  echo "#pragma once"
  echo
  echo "static const char CA_BUNDLE_PEM[] PROGMEM ="
  grep -v '^#' "$TMP" | grep -v '^$' | sed 's/\\/\\\\/g; s/"/\\"/g; s/^/"/; s/$/\\n"/'
  echo ";"
} > "$OUT"

rm -f "$TMP"
echo "wrote $OUT"
