#!/usr/bin/env python3
"""Generate the bundled default pet, or a pet payload for a running terminal.

Every unit ships showing a pet before anyone plugs it in, so the default is
compiled into the image as a PROGMEM bitmap. Attendees replace it by syncing
their own — see tools/dash_sync.py.

Usage:
  tools/gen_pet.py                         # bundle the built-in codex pet
  tools/gen_pet.py --pet gauge             # bundle a pet from ~/.codex/pets
  tools/gen_pet.py --pet path/to/sheet.webp
  tools/gen_pet.py --hex                   # print hex for a content.push
  tools/gen_pet.py --pgm out.pgm           # eyeball the conversion

Output: firmware/pet_asset.h
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import imaging
from pet import DEFAULT_PET, PET_BYTES, PET_H, PET_W, PetError, resolve_pet, sheet_bits

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "firmware" / "pet_asset.h"


def emit_header(label: str, bits: bytes, row: int, col: int) -> str:
    body = ",\n  ".join(
        ", ".join(f"0x{b:02X}" for b in bits[i : i + 12])
        for i in range(0, len(bits), 12)
    )
    return f"""// Auto-generated by tools/gen_pet.py from the "{label}" pet, cell ({row},{col}).
// Regenerate to change the pet every unit ships with; no firmware edits needed.
#pragma once

#include <Arduino.h>

#define PET_ASSET_PRESENT 1
static const char PET_ASSET_NAME[] = "{label}";

// Packed 1-bit, MSB-first, row-major. Set bit = black ink. {PET_W}x{PET_H}.
static const uint8_t PET_ASSET_BITMAP[{len(bits)}] PROGMEM = {{
  {body}
}};
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pet", default=DEFAULT_PET, metavar="ID|PATH")
    ap.add_argument("--row", type=int, default=0, help="atlas row (0 = idle)")
    ap.add_argument("--col", type=int, default=0, help="atlas column")
    ap.add_argument(
        "--threshold",
        type=int,
        default=190,
        help="ink cutoff, 0-255; lower keeps only the darkest art (default 190)",
    )
    ap.add_argument("--hex", action="store_true", help="print hex instead of writing a header")
    ap.add_argument("--pgm", type=Path, default=None, help="also write a preview PGM")
    ap.add_argument("--offline", action="store_true", help="never download a built-in pet")
    args = ap.parse_args()

    try:
        label, sheet = resolve_pet(args.pet, allow_download=not args.offline)
        bits = sheet_bits(sheet, args.row, args.col, args.threshold)
    except (PetError, imaging.ImagingError) as exc:
        raise SystemExit(f"gen_pet: {exc}")
    if len(bits) != PET_BYTES:
        raise SystemExit(f"expected {PET_BYTES} bytes, produced {len(bits)}")

    if args.pgm:
        args.pgm.write_bytes(imaging.bits_to_pgm(bits, PET_W, PET_H))
        print(f"wrote {args.pgm}", file=sys.stderr)

    if args.hex:
        print(bits.hex())
        return 0

    OUT.write_text(emit_header(label, bits, args.row, args.col), encoding="utf-8")
    ink = sum(bin(b).count("1") for b in bits)
    print(
        f"wrote {OUT} — {label} cell ({args.row},{args.col}), "
        f"{PET_W}x{PET_H}, {len(bits)} bytes, {100 * ink / (PET_W * PET_H):.0f}% ink"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
