#!/usr/bin/env python3
"""Generate the first-boot splash faces.

The very first boot after factory flash shows a row of Dev Day mascot faces —
the branding moment every attendee sees before they've done anything. This
script turns artwork into the PROGMEM bitmaps the firmware blits.

**This is the drop-in point for OpenAI design's final art.** Point it at the
approved PNGs and rebuild; no firmware edits, no code review:

  tools/gen_splash.py art/face-*.png

With no arguments it regenerates the placeholder set, so the build stays green
while the artwork is still being approved.

Source art should be square-ish, on a transparent or white background. Faces are
drawn side by side, so 3-5 of them read best.

Output: firmware/devday_splash.h
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import imaging

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "firmware" / "devday_splash.h"

# One face's bitmap. 144x144 fills a useful share of the 480px-tall panel with
# a row of four, and divides into whole bytes per row. The firmware scales
# whatever it is given to fit, so changing this does not need a firmware edit.
FACE_W = 144
FACE_H = 144
FACE_BYTES = (FACE_W * FACE_H) // 8


def placeholder_faces() -> list[tuple[str, bytearray]]:
    """Stand-in mascots: circle-bodied agents, in the spirit of "circle guys".

    Deliberately simple — these exist so the firmware compiles and the layout
    can be reviewed before the real art lands. Replace them.
    """
    faces: list[tuple[str, bytearray]] = []
    cx = cy = FACE_W / 2
    radius = FACE_W * 0.42

    # (label, eye y offset, eye radius, mouth arc, mouth width)
    specs = [
        ("idle", -0.10, 0.055, 0.0, 0.30),
        ("blink", -0.10, 0.012, 0.0, 0.24),
        ("happy", -0.12, 0.055, 0.5, 0.34),
        ("look", -0.10, 0.055, -0.3, 0.20),
    ]

    for label, eye_dy, eye_r, arc, mouth_w in specs:
        bits = [False] * (FACE_W * FACE_H)

        def put(x: int, y: int) -> None:
            if 0 <= x < FACE_W and 0 <= y < FACE_H:
                bits[y * FACE_W + x] = True

        # Body: a filled ring, so the face reads as a shape not a blob.
        stroke = max(3.0, FACE_W * 0.05)
        for y in range(FACE_H):
            for x in range(FACE_W):
                d = math.hypot(x - cx + 0.5, y - cy + 0.5)
                if radius - stroke <= d <= radius:
                    put(x, y)

        eye_y = int(cy + eye_dy * FACE_H)
        for sign in (-1, 1):
            ex = cx + sign * FACE_W * 0.16
            er = FACE_W * eye_r
            for y in range(int(eye_y - er) - 1, int(eye_y + er) + 2):
                for x in range(int(ex - er) - 1, int(ex + er) + 2):
                    if math.hypot(x - ex + 0.5, y - eye_y + 0.5) <= er:
                        put(x, y)

        # Mouth: a shallow arc, curvature signed by `arc`.
        half = int(FACE_W * mouth_w / 2)
        my = int(cy + FACE_H * 0.16)
        for dx in range(-half, half + 1):
            t = dx / max(half, 1)
            dy = int(arc * FACE_H * 0.09 * (1 - t * t))
            put(int(cx + dx), my + dy)
            put(int(cx + dx), my + dy + 1)

        out = bytearray(FACE_BYTES)
        for i, on in enumerate(bits):
            if on:
                out[i >> 3] |= 0x80 >> (i & 7)
        faces.append((label, out))
    return faces


def load_faces(paths: list[Path], threshold: int) -> list[tuple[str, bytearray]]:
    faces = []
    for path in paths:
        bits = imaging.sprite_to_bits(
            path.read_bytes(), FACE_W, FACE_H, None, threshold
        )
        faces.append((path.stem, bits))
    return faces


def emit_header(faces: list[tuple[str, bytearray]], source: str) -> str:
    rows = []
    for _, bits in faces:
        body = ",\n    ".join(
            ", ".join(f"0x{b:02X}" for b in bits[i : i + 12])
            for i in range(0, len(bits), 12)
        )
        rows.append("  {\n    " + body + "\n  }")
    names = ", ".join(f'"{label}"' for label, _ in faces)
    return f"""// Auto-generated by tools/gen_splash.py from {source}.
// Regenerate with the approved artwork to change what every unit shows at
// first boot; no firmware edits needed.
#pragma once

#include <Arduino.h>

static constexpr uint8_t SPLASH_FACE_W = {FACE_W};
static constexpr uint8_t SPLASH_FACE_H = {FACE_H};
static constexpr uint8_t SPLASH_FACE_COUNT = {len(faces)};
static const char* const SPLASH_FACE_NAMES[{len(faces)}] = {{{names}}};

// Packed 1-bit, MSB-first, row-major. Set bit = black ink.
static const uint8_t SPLASH_FACES[{len(faces)}][{FACE_BYTES}] PROGMEM = {{
{",\n".join(rows)}
}};
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("art", nargs="*", type=Path, help="face images (PNG/WebP)")
    ap.add_argument("--threshold", type=int, default=190)
    ap.add_argument("--pgm-dir", type=Path, default=None, help="write previews here")
    args = ap.parse_args()

    if args.art:
        faces = load_faces(args.art, args.threshold)
        source = ", ".join(p.name for p in args.art)
    else:
        faces = placeholder_faces()
        source = "built-in placeholders (awaiting OpenAI design artwork)"

    if not faces:
        raise SystemExit("no faces to write")

    if args.pgm_dir:
        args.pgm_dir.mkdir(parents=True, exist_ok=True)
        for label, bits in faces:
            (args.pgm_dir / f"{label}.pgm").write_bytes(
                imaging.bits_to_pgm(bits, FACE_W, FACE_H)
            )
        print(f"wrote previews to {args.pgm_dir}", file=sys.stderr)

    OUT.write_text(emit_header(faces, source), encoding="utf-8")
    print(
        f"wrote {OUT} — {len(faces)} face(s) at {FACE_W}x{FACE_H} from {source}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
