#!/usr/bin/env bash
# Generate a local RSA-2048 update-signing keypair and embed the public key in
# the firmware as ota_pubkey.h.
#
# NOTE: The PRODUCTION private key lives in 1Password and is never committed.
# This script is for local development. To build with the production key,
# drop prod_update_key.pem into tools/keys/ (gitignored) and re-run with
# PUB_ONLY=1 to regenerate the header from it.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KEYS="$ROOT/tools/keys"
PRIV="$KEYS/update_key.pem"
PUB="$KEYS/update_key.pub.pem"
DER="$KEYS/update_key.pub.der"
HDR="$ROOT/firmware/devday_terminal/ota_pubkey.h"

mkdir -p "$KEYS"

if [[ "${PUB_ONLY:-0}" != "1" && ! -f "$PRIV" ]]; then
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$PRIV"
  chmod 600 "$PRIV"
  echo "generated development private key: $PRIV (DO NOT COMMIT)"
fi

openssl rsa -in "$PRIV" -pubout -out "$PUB" 2>/dev/null
openssl rsa -pubin -in "$PUB" -outform DER -out "$DER" 2>/dev/null

{
  echo "// Auto-generated by tools/gen_keys.sh - RSA-2048 update verification key (public only)."
  echo "#pragma once"
  echo
  echo "#include <Arduino.h>"
  echo
  SIZE=$(stat -f%z "$DER")
  echo "static const size_t OTA_PUBKEY_DER_LEN = ${SIZE};"
  echo "static const uint8_t OTA_PUBKEY_DER[] PROGMEM = {"
  xxd -i < "$DER" | sed 's/^/  /'
  echo "};"
} > "$HDR"

echo "wrote $HDR"
