#!/usr/bin/env python3
"""Generate qr_recipe.h - a fixed QR code bitmap for the hardware recipe URL.

Usage: python3 tools/gen_qr.py [url]
Output: firmware/devday_terminal/qr_recipe.h
"""
import sys
from pathlib import Path

import qrcode

URL = sys.argv[1] if len(sys.argv) > 1 else "https://github.com/jjeremycai/devday-firmware"
OUT = Path(__file__).resolve().parent.parent / "firmware" / "devday_terminal" / "qr_recipe.h"

qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, border=2, box_size=1)
qr.add_data(URL)
qr.make(fit=True)
matrix = qr.get_matrix()
size = len(matrix)

rows = []
for r in matrix:
    byte_row = []
    for i in range(0, size, 8):
        b = 0
        for j, bit in enumerate(r[i : i + 8]):
            if bit:
                b |= 0x80 >> j
        byte_row.append(b)
    rows.append(byte_row)

row_bytes = (size + 7) // 8
body = ",\n  ".join(", ".join(f"0x{b:02X}" for b in row) for row in rows)

OUT.write_text(
    f"""// Auto-generated by tools/gen_qr.py for: {URL}
#pragma once

#include <Arduino.h>

static constexpr uint8_t QR_RECIPE_SIZE = {size};
static constexpr uint8_t QR_RECIPE_ROW_BYTES = {row_bytes};

static const uint8_t QR_RECIPE_BITMAP[{size}][{row_bytes}] PROGMEM = {{
  {body}
}};
""",
    encoding="utf-8",
)
print(f"wrote {OUT} ({size}x{size} modules) for {URL}")
