#include "cards.h"

#include <SPI.h>
#include <TFT_eSPI.h> // Seeed_GFX (gfxfont.h provides the standard FreeSans fonts)
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

#include "config.h"
#include "buttons.h"
#include "qr_recipe.h"
// Generated by tools/gen_pet.py. Regenerating it changes the bundled pet
// without touching this file.
#include "pet_asset.h"

#ifdef EPAPER_ENABLE
static EPaper epaper = EPaper();
#endif

// 24×24 OpenAI blossom — 1-bit, rasterized from the official openai-blossom.svg
static const uint8_t kBlossom24[72] = {
  0x00, 0x00, 0x00,
  0x00, 0xFC, 0x00,
  0x03, 0x8F, 0xC0,
  0x03, 0x0F, 0xF0,
  0x06, 0x3C, 0x38,
  0x0C, 0x70, 0x18,
  0x3C, 0xC3, 0x8C,
  0x34, 0xCF, 0xEC,
  0x64, 0xFC, 0x7C,
  0x44, 0xFF, 0x1C,
  0x44, 0xC3, 0x8E,
  0x46, 0xC3, 0xE6,
  0x67, 0xC3, 0x62,
  0x71, 0xC3, 0x22,
  0x38, 0xFF, 0x22,
  0x3E, 0x3F, 0x26,
  0x37, 0xF3, 0x2C,
  0x31, 0xC3, 0x3C,
  0x18, 0x0E, 0x30,
  0x1C, 0x3C, 0x60,
  0x0F, 0xF0, 0xC0,
  0x03, 0xF1, 0xC0,
  0x00, 0x3F, 0x00,
  0x00, 0x00, 0x00,
};

static void drawBlossomIcon(int16_t x0, int16_t y0) {
#ifdef EPAPER_ENABLE
  for (int16_t y = 0; y < 24; y++) {
    for (int16_t x = 0; x < 24; x++) {
      size_t bit = (size_t)y * 24 + (size_t)x;
      if (kBlossom24[bit / 8] & (0x80 >> (bit % 8))) {
        epaper.drawPixel(x0 + x, y0 + y, TFT_BLACK);
      }
    }
  }
#endif
}

static constexpr int16_t W = 800;
static constexpr int16_t H = 480;
static constexpr int16_t MARGIN = 28;

// Brutalist tab strip: heavy inversion, tight type, no decoration
static void pageTabs(const char* current) {
#ifdef EPAPER_ENABLE
  static const char* kIds[3] = {"dash", "weather", "agenda"};
  static const char* kLabels[3] = {"1 USAGE", "2 WEATHER", "3 AGENDA"};
  const int16_t tw = 210, th = 28, gap = 14;
  const int16_t total = 3 * tw + 2 * gap;
  int16_t x = (W - total) / 2;
  const int16_t y = H - 10 - th;
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.setTextDatum(MC_DATUM);
  for (uint8_t i = 0; i < 3; i++) {
    bool active = current != nullptr && strcmp(current, kIds[i]) == 0;
    if (active) {
      epaper.fillRoundRect(x, y, tw, th, 4, TFT_BLACK);
      epaper.setTextColor(TFT_WHITE, TFT_BLACK);
    } else {
      epaper.drawRoundRect(x, y, tw, th, 4, TFT_BLACK);
      epaper.setTextColor(TFT_BLACK, TFT_WHITE);
    }
    epaper.drawString(kLabels[i], x + tw / 2, y + th / 2 + 1, GFXFF);
    x += tw + gap;
  }
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

// Battery gauge: outline + nub, fill level = charge percent.
static void drawBatteryIcon(int16_t x, int16_t y, uint8_t pct) {
#ifdef EPAPER_ENABLE
  epaper.drawRect(x, y, 18, 11, TFT_BLACK);
  epaper.fillRect(x + 19, y + 3, 2, 5, TFT_BLACK); // nub
  if (pct > 100) pct = 100;
  int16_t fill = (int16_t)((uint16_t)pct * 14 / 100);
  if (fill > 0) epaper.fillRect(x + 2, y + 2, fill, 7, TFT_BLACK);
#endif
}

// Compact 1-bit Wi-Fi mark. Connected uses stepped arcs; disconnected keeps
// the same silhouette with a separated slash, so state is visible without
// relying on grey or a text label.
static void drawWifiIcon(int16_t x, int16_t y, bool connected) {
#ifdef EPAPER_ENABLE
  epaper.fillRect(x + 5, y, 6, 1, TFT_BLACK);
  epaper.fillRect(x + 2, y + 1, 3, 1, TFT_BLACK);
  epaper.fillRect(x + 11, y + 1, 3, 1, TFT_BLACK);
  epaper.fillRect(x + 1, y + 2, 2, 1, TFT_BLACK);
  epaper.fillRect(x + 13, y + 2, 2, 1, TFT_BLACK);
  epaper.drawPixel(x, y + 3, TFT_BLACK);
  epaper.drawPixel(x + 15, y + 3, TFT_BLACK);

  epaper.fillRect(x + 6, y + 4, 4, 1, TFT_BLACK);
  epaper.fillRect(x + 4, y + 5, 2, 1, TFT_BLACK);
  epaper.fillRect(x + 10, y + 5, 2, 1, TFT_BLACK);
  epaper.drawPixel(x + 3, y + 6, TFT_BLACK);
  epaper.drawPixel(x + 12, y + 6, TFT_BLACK);

  epaper.fillRect(x + 7, y + 7, 2, 1, TFT_BLACK);
  epaper.drawPixel(x + 6, y + 8, TFT_BLACK);
  epaper.drawPixel(x + 9, y + 8, TFT_BLACK);
  epaper.fillRect(x + 7, y + 10, 2, 2, TFT_BLACK);

  if (!connected) {
    // A 2 px core with a 1 px paper moat remains a slash at arm's length;
    // the old 1 px line broke the tiny arcs into what looked like panel noise.
    // Extend past the glyph so neither endpoint disappears into an arc.
    for (int16_t i = -2; i < 14; i++) {
      epaper.fillRect(x + 1 + i, y + i, 4, 1, TFT_WHITE);
    }
    for (int16_t i = -2; i < 14; i++) {
      epaper.fillRect(x + 2 + i, y + i, 2, 1, TFT_BLACK);
    }
  }
#endif
}

// ---------------------------------------------------------------------------
// Weather condition icons
//
// Solid silhouettes: at 20-36px on 1-bit e-paper a stroked glyph turns to
// noise, a filled shape stays legible from across a desk. (x, y) is the top
// left of an s-by-s box; the glyph centres itself inside it.
// ---------------------------------------------------------------------------
enum class WxIcon : uint8_t { NONE, SUN, PARTLY, CLOUD, RAIN, SNOW, STORM, FOG };

static WxIcon wxIconFor(const String& cond) {
  String s = cond;
  s.toLowerCase();
  if (s.indexOf("thunder") >= 0 || s.indexOf("storm") >= 0) return WxIcon::STORM;
  if (s.indexOf("snow") >= 0 || s.indexOf("sleet") >= 0) return WxIcon::SNOW;
  if (s.indexOf("rain") >= 0 || s.indexOf("drizzle") >= 0 || s.indexOf("shower") >= 0)
    return WxIcon::RAIN;
  if (s.indexOf("fog") >= 0 || s.indexOf("mist") >= 0 || s.indexOf("haze") >= 0)
    return WxIcon::FOG;
  if (s.indexOf("partly") >= 0 || s.indexOf("mainly") >= 0) return WxIcon::PARTLY;
  if (s.indexOf("cloud") >= 0 || s.indexOf("overcast") >= 0) return WxIcon::CLOUD;
  if (s.indexOf("clear") >= 0 || s.indexOf("sun") >= 0) return WxIcon::SUN;
  return WxIcon::NONE;
}

#ifdef EPAPER_ENABLE
static void wxSunDisc(int16_t cx, int16_t cy, int16_t s, uint16_t color) {
  const int16_t r = s * 22 / 100;
  const int16_t gap = r + s * 6 / 100; // where rays start
  const int16_t len = s * 14 / 100;    // ray length
  const int16_t th = s >= 30 ? 3 : 2;  // ray thickness
  epaper.fillCircle(cx, cy, r, color);
  epaper.fillRect(cx - th / 2, cy - gap - len, th, len, color); // N
  epaper.fillRect(cx - th / 2, cy + gap, th, len, color);       // S
  epaper.fillRect(cx - gap - len, cy - th / 2, len, th, color); // W
  epaper.fillRect(cx + gap, cy - th / 2, len, th, color);       // E
  // Diagonal rays: thickness-sized squares stepped along the 45° line.
  const int16_t d0 = (gap * 100 + 70) / 141;
  const int16_t dn = (len * 100 + 70) / 141;
  for (int16_t k = 0; k < dn; k++) {
    for (int8_t sx = -1; sx <= 1; sx += 2) {
      for (int8_t sy = -1; sy <= 1; sy += 2) {
        epaper.fillRect(cx + sx * (d0 + k) - th / 2, cy + sy * (d0 + k) - th / 2, th, th, color);
      }
    }
  }
}

static void wxCloudShape(int16_t cx, int16_t cy, int16_t s, uint16_t color) {
  // Two lobes over a rounded base; (cx, cy) is the base's centre.
  const int16_t base_w = s * 76 / 100;
  const int16_t base_h = s * 26 / 100;
  epaper.fillCircle(cx - base_w / 2 + base_h / 2 + s * 4 / 100, cy - s * 6 / 100, s * 16 / 100, color);
  epaper.fillCircle(cx + s * 6 / 100, cy - s * 14 / 100, s * 22 / 100, color);
  epaper.fillRoundRect(cx - base_w / 2, cy - base_h / 2, base_w, base_h, base_h / 2, color);
}

static void drawWeatherIcon(int16_t x, int16_t y, int16_t s, const String& cond) {
  const WxIcon icon = wxIconFor(cond);
  if (icon == WxIcon::NONE) return;
  const int16_t cx = x + s / 2;
  const int16_t cy = y + s / 2;
  switch (icon) {
    case WxIcon::SUN:
      wxSunDisc(cx, cy, s, TFT_BLACK);
      break;
    case WxIcon::PARTLY: {
      // Sun peeking out top-right; an oversized white cloud first, so a
      // margin of paper separates the two shapes.
      wxSunDisc(cx + s * 18 / 100, cy - s * 18 / 100, s * 64 / 100, TFT_BLACK);
      const int16_t ccx = cx - s * 4 / 100;
      const int16_t ccy = cy + s * 16 / 100;
      wxCloudShape(ccx, ccy, s * 116 / 100, TFT_WHITE);
      wxCloudShape(ccx, ccy, s * 88 / 100, TFT_BLACK);
      break;
    }
    case WxIcon::CLOUD:
      wxCloudShape(cx, cy + s * 6 / 100, s, TFT_BLACK);
      break;
    case WxIcon::RAIN: {
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, TFT_BLACK);
      const int16_t drop = s * 16 / 100 < 4 ? 4 : s * 16 / 100;
      for (int8_t i = 0; i < 3; i++) {
        const int16_t dx = cx - s * 22 / 100 + i * (s * 22 / 100);
        const int16_t dy = cy + s * 10 / 100;
        for (int16_t k = 0; k < drop; k++) {
          epaper.fillRect(dx - k / 2, dy + k, 2, 2, TFT_BLACK); // slanted drop
        }
      }
      break;
    }
    case WxIcon::SNOW: {
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, TFT_BLACK);
      for (int8_t i = 0; i < 3; i++) {
        const int16_t fx = cx - s * 22 / 100 + i * (s * 22 / 100);
        const int16_t fy = cy + s * 16 / 100 + (i == 1 ? s * 10 / 100 : 0);
        epaper.fillCircle(fx, fy, 2, TFT_BLACK);
      }
      break;
    }
    case WxIcon::STORM: {
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, TFT_BLACK);
      // Bolt: a staircase of slabs stepping down-left, notched out of the
      // cloud by a white pass so the two shapes never merge into one blob.
      const int16_t bw = s * 18 / 100 < 4 ? 4 : s * 18 / 100;
      const int16_t step = s * 10 / 100 < 3 ? 3 : s * 10 / 100;
      const int16_t bx = cx + s * 2 / 100;
      const int16_t by = cy - s * 2 / 100;
      for (int8_t pass = 0; pass < 2; pass++) {
        const int16_t in = pass == 0 ? 2 : 0;
        const uint16_t color = pass == 0 ? TFT_WHITE : TFT_BLACK;
        epaper.fillRect(bx - in, by - in, bw + 2 * in, step + 1 + 2 * in, color);
        epaper.fillRect(bx - step / 2 - 1 - in, by + step - in, bw + 2 * in, step + 1 + 2 * in, color);
        epaper.fillRect(bx - step - 2 - in, by + 2 * step - in, bw - 2 + 2 * in, step + 1 + 2 * in, color);
      }
      break;
    }
    case WxIcon::FOG:
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, TFT_BLACK);
      epaper.fillRect(cx - s * 34 / 100, cy + s * 12 / 100, s * 68 / 100, 2, TFT_BLACK);
      epaper.fillRect(cx - s * 26 / 100, cy + s * 22 / 100, s * 52 / 100, 2, TFT_BLACK);
      break;
    default:
      break;
  }
}
#endif

static void header(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  // Blossom at left; date, Wi-Fi state, battery gauge and percentage at right.
  drawBlossomIcon(MARGIN, 8);
  epaper.setFreeFont(&FreeSans9pt7b);
  const String battery_pct = String(st.battery_pct) + "%";
  const int16_t battery_pct_w = epaper.textWidth(battery_pct, GFXFF);
  const int16_t battery_x = W - MARGIN - battery_pct_w - 4 - 21;
  const int16_t wifi_x = battery_x - 22;
  epaper.setTextDatum(TR_DATUM);
  if (c.header_date.length()) epaper.drawString(c.header_date, wifi_x - 4, 12, GFXFF);
  // Both icons and the percentage share the 9pt text midline.
  drawWifiIcon(wifi_x, 13, st.wifi_connected);
  drawBatteryIcon(battery_x, 13, st.battery_pct);
  epaper.drawString(battery_pct, W - MARGIN, 12, GFXFF);
  // brutalist hairline + 1px double-rule for density
  epaper.drawFastHLine(MARGIN, 42, W - 2 * MARGIN, TFT_BLACK);
  epaper.drawFastHLine(MARGIN, 44, W - 2 * MARGIN, TFT_BLACK);
#endif
}

// Payload strings are attacker-shaped as far as layout is concerned: nothing
// upstream bounds their length, drawString does not clip, and e-paper has no
// scroll. Trim to the space actually available, with an ellipsis so the reader
// can tell something was cut.
static String fit(const String& text, int16_t max_w) {
#ifdef EPAPER_ENABLE
  if (text.length() == 0 || epaper.textWidth(text, GFXFF) <= max_w) return text;
  // Plain ASCII: the GFX free fonts stop at 0x7E, so a U+2026 ellipsis would
  // render as nothing at all on the panel.
  const char* kCut = "...";
  int16_t budget = max_w - epaper.textWidth(kCut, GFXFF);
  if (budget <= 0) return kCut;

  // Longest prefix that fits, stepping only on UTF-8 character boundaries —
  // payloads carry multi-byte glyphs (the ° in every temperature) and half a
  // sequence is not valid text. Lengths here are tens of characters, so a
  // linear walk costs less than the string churn of a binary search.
  size_t n = text.length();
  while (n > 0) {
    while (n > 0 && ((uint8_t)text.charAt(n) & 0xC0) == 0x80) n--; // snap to boundary
    if (epaper.textWidth(text.substring(0, n), GFXFF) <= budget) break;
    n--;
  }
  return text.substring(0, n) + kCut;
#else
  (void)max_w;
  return text;
#endif
}

static void apHint(const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  if (st.ap_hint.length() > 0) {
    // Setup portal credentials, front and center while the AP is up.
    epaper.setFreeFont(&FreeSans12pt7b);
    epaper.setTextDatum(BC_DATUM);
    epaper.drawString(st.ap_hint, W / 2, H - 58, GFXFF);
  }
#endif
}

// Every page that has nothing to show yet says the same thing: what this page
// will be, and the one sentence that makes it real. The tab strip already
// numbers the other pages, so there is nothing else to teach.
static void renderEmpty(const CardContent& c, const RenderStatus& st, const char* tab,
                        const char* label, const char* headline, const char* ask) {
#ifdef EPAPER_ENABLE
  header(c, st);

  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(label, MARGIN, 86, GFXFF);
  epaper.drawFastHLine(MARGIN, 108, 48, TFT_BLACK);

  epaper.setFreeFont(&FreeSans18pt7b);
  epaper.setTextDatum(MC_DATUM);
  epaper.drawString(headline, W / 2, 204, GFXFF);
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.drawString("Connect over USB and ask Codex:", W / 2, 246, GFXFF);

  // This is a real prompt: the terminal is waiting for exactly this request.
  // Centre the prompt and static e-paper cursor as one unit.
  epaper.setFreeFont(&FreeMono12pt7b);
  const int16_t cursor_gap = 6;
  const int16_t cursor_w = 10;
  const int16_t cursor_h = 18;
  String prompt = fit(String("> ") + ask, W - 2 * MARGIN - cursor_gap - cursor_w);
  const int16_t prompt_w = epaper.textWidth(prompt, GFXFF);
  const int16_t prompt_x = (W - prompt_w - cursor_gap - cursor_w) / 2;
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(prompt, prompt_x, 278, GFXFF);
  epaper.fillRect(prompt_x + prompt_w + cursor_gap, 278 - cursor_h / 2,
                  cursor_w, cursor_h, TFT_BLACK);

  // The splash character waits below the prompt on otherwise empty pages.
  // Portal credentials use this band instead, so they always take priority.
  if (st.ap_hint.length() == 0) {
    const int16_t dome_r = 64;
    const int16_t dome_cx = W / 2;
    const int16_t dome_base = 426;
    epaper.fillCircle(dome_cx, dome_base, dome_r, TFT_BLACK);
    epaper.fillRect(dome_cx - dome_r, dome_base, 2 * dome_r + 1, dome_r + 1, TFT_WHITE);

    const int16_t eye_dx = dome_r / 2;
    const int16_t eye_y = dome_base - dome_r + dome_r * 58 / 100;
    const int16_t arm = 26;
    const int16_t stroke = 4;
    for (int8_t side = -1; side <= 1; side += 2) {
      const int16_t ex = dome_cx + side * eye_dx;
      epaper.fillRect(ex - arm / 2, eye_y - stroke / 2, arm, stroke, TFT_WHITE);
      epaper.fillRect(ex - stroke / 2, eye_y - arm / 2, stroke, arm, TFT_WHITE);
    }
  }

  apHint(st);
  pageTabs(tab);
#endif
}

static void renderBuild(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  header(c, st);

  String state = c.build_state;
  state.toUpperCase();
  epaper.setFreeFont(&FreeSansBold24pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(state, MARGIN, 90, GFXFF);

  epaper.setFreeFont(&FreeSans18pt7b);
  epaper.drawString(c.build_title, MARGIN, 170, GFXFF);

  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.drawString(c.build_detail, MARGIN, 230, GFXFF);

  if (c.build_updated_at.length() > 0) {
    epaper.setFreeFont(&FreeSans9pt7b);
    epaper.drawString("Updated " + c.build_updated_at, MARGIN, 280, GFXFF);
  }

  // Machine self-report: fixed mono columns instead of alignment by spaces.
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(TL_DATUM);
  const int16_t y = 324;
  const int16_t value_x = MARGIN + 110;
  const int16_t value_w = W - MARGIN - value_x;
  epaper.drawString("firmware", MARGIN, y, GFXFF);
  epaper.drawString(fit(String(FW_NAME " v" FW_VERSION " (") + st.fw_hash + ")", value_w),
                    value_x, y, GFXFF);
  epaper.drawString("battery", MARGIN, y + 28, GFXFF);
  epaper.drawString(fit(String(st.battery_v, 2) + " V (" + String(st.battery_pct) + "%)", value_w),
                    value_x, y + 28, GFXFF);
  epaper.drawString("display", MARGIN, y + 56, GFXFF);
  epaper.drawString("UC8179 800x480  combo 502", value_x, y + 56, GFXFF);
  epaper.drawString("link", MARGIN, y + 84, GFXFF);
  epaper.drawString(fit(st.connection, value_w), value_x, y + 84, GFXFF);

  apHint(st);
  pageTabs("build");
#endif
}

static String formatAgendaTime(const String& raw) {
  String value = raw;
  value.trim();
  if (value.length() == 0) return value;

  // Accept plain times as well as ISO-style date-time values.
  int time_start = 0;
  for (size_t i = 0; i < value.length(); i++) {
    if (value.charAt(i) == 'T' || value.charAt(i) == 't') {
      time_start = (int)i + 1;
    }
  }
  if (time_start > 0 && time_start < (int)value.length()) {
    value = value.substring(time_start, value.length());
  }

  int colon = -1;
  for (size_t i = 0; i < value.length(); i++) {
    if (value.charAt(i) == ':') {
      colon = (int)i;
      break;
    }
  }
  if (colon < 1 || colon + 1 >= (int)value.length()) return raw;

  int hour_start = colon - 1;
  while (hour_start >= 0 && isdigit((unsigned char)value.charAt(hour_start))) hour_start--;
  hour_start++;
  String hour_text = value.substring(hour_start, colon);

  int minute_end = colon + 1;
  while (minute_end < (int)value.length() && isdigit((unsigned char)value.charAt(minute_end))) {
    minute_end++;
  }
  String minute_text = value.substring(colon + 1, minute_end);
  if (hour_text.length() == 0 || minute_text.length() == 0) return raw;

  int hour = atoi(hour_text.c_str());
  int minute = atoi(minute_text.c_str());
  if (minute < 0 || minute > 59) return raw;

  String upper = value;
  upper.toUpperCase();
  bool has_am = false;
  bool has_pm = false;
  for (size_t i = 0; i + 1 < upper.length(); i++) {
    if (upper.charAt(i) == 'A' && upper.charAt(i + 1) == 'M') has_am = true;
    if (upper.charAt(i) == 'P' && upper.charAt(i + 1) == 'M') has_pm = true;
  }

  bool pm = has_pm;
  if (has_am || has_pm) {
    if (hour < 1 || hour > 12) return raw;
  } else {
    if (hour < 0 || hour > 23) return raw;
    pm = hour >= 12;
    hour %= 12;
    if (hour == 0) hour = 12;
  }

  return String(hour) + ":" + (minute < 10 ? "0" : "") + String(minute) + (pm ? " PM" : " AM");
}

static void renderAgenda(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  header(c, st);

  if (!contentHasAgenda(c)) {
    renderEmpty(c, st, "agenda", "AGENDA", "No events today", "put my calendar on my terminal");
    return;
  }

  // Date row: tight, uppercase label + hairline
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.setTextDatum(TL_DATUM);
  String adate = c.agenda_date; adate.toUpperCase();
  epaper.drawString(adate, MARGIN, 68, GFXFF);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString(String(c.agenda_count) + " EVENTS", W - MARGIN, 68, GFXFF);
  epaper.drawFastHLine(MARGIN, 88, W - 2 * MARGIN, TFT_BLACK);

  const int16_t row_h = 68;
  const int16_t gap = 8;
  const int16_t y0 = 102;
  const size_t rows =
      c.agenda_count < CardContent::AGENDA_MAX ? c.agenda_count : CardContent::AGENDA_MAX;

  // Timeline spine, drawn between the first and last marker rather than to a
  // fixed height — a short day used to leave it dangling past the last event.
  const int16_t spineX = MARGIN + 14;
  const int16_t first_dot = y0 + row_h / 2;
  const int16_t last_dot = y0 + (int16_t)(rows - 1) * (row_h + gap) + row_h / 2;
  if (rows > 1) {
    epaper.drawFastVLine(spineX, first_dot, last_dot - first_dot, TFT_BLACK);
  }

  for (size_t i = 0; i < rows; i++) {
    int16_t ry = y0 + (int16_t)i * (row_h + gap);
    epaper.drawRoundRect(MARGIN + 28, ry, W - 2 * MARGIN - 28, row_h, 4, TFT_BLACK);

    // Filled marker for what is next, hollow for the rest.
    if (i == 0) {
      epaper.fillCircle(spineX, ry + row_h / 2, 7, TFT_BLACK);
    } else {
      epaper.drawCircle(spineX, ry + row_h / 2, 5, TFT_BLACK);
    }

    // The time is vertically centred in its fixed column. Event text stays
    // left aligned, but is vertically centred as a two-line block instead of
    // being anchored to the time's much larger glyph baseline.
    const int16_t time_x = MARGIN + 38;
    const int16_t text_left = MARGIN + 210;
    const int16_t text_right = W - MARGIN - 16;
    const int16_t text_w = text_right - text_left;
    const int16_t center_y = ry + row_h / 2;

    epaper.setFreeFont(&FreeMonoBold18pt7b);
    epaper.setTextDatum(ML_DATUM);
    epaper.drawString(formatAgendaTime(c.agenda_time[i]), time_x, center_y, GFXFF);

    const bool has_detail = c.agenda_detail[i].length() > 0;
    epaper.setFreeFont(&FreeSans12pt7b);
    epaper.setTextDatum(has_detail ? BL_DATUM : ML_DATUM);
    epaper.drawString(fit(c.agenda_title[i], text_w), text_left,
                      has_detail ? center_y - 2 : center_y, GFXFF);

    if (has_detail) {
      // Sentence case: room names and people stay human prose under the title
      // while machine-derived times remain monospace.
      epaper.setFreeFont(&FreeSans9pt7b);
      epaper.setTextDatum(TL_DATUM);
      epaper.drawString(fit(c.agenda_detail[i], text_w), text_left,
                        center_y + 4, GFXFF);
    }
  }

  apHint(st);
  pageTabs("agenda");
#endif
}

static void drawQr(int16_t x, int16_t y, uint8_t scale) {
#ifdef EPAPER_ENABLE
  for (uint8_t r = 0; r < QR_RECIPE_SIZE; r++) {
    for (uint8_t col = 0; col < QR_RECIPE_SIZE; col++) {
      uint8_t b = pgm_read_byte(&QR_RECIPE_BITMAP[r][col / 8]);
      if (b & (0x80 >> (col % 8))) {
        epaper.fillRect(x + col * scale, y + r * scale, scale, scale, TFT_BLACK);
      }
    }
  }
#endif
}

static void renderYours(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  header(c, st);

  epaper.setFreeFont(&FreeSansBold24pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString("This terminal is open", MARGIN, 96, GFXFF);

  epaper.setFreeFont(&FreeSans12pt7b);
  int16_t y = 180;
  epaper.drawString("Flash your own firmware over USB -", MARGIN, y, GFXFF);
  epaper.drawString("no keys, no locks.", MARGIN, y + 32, GFXFF);
  epaper.drawString("Scan the code for the hardware recipe:", MARGIN, y + 76, GFXFF);
  epaper.drawString("parts, wiring, and the exact Arduino +", MARGIN, y + 108, GFXFF);
  epaper.drawString("Codex recipe to build a replacement app.", MARGIN, y + 140, GFXFF);

  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.drawString(fit(RECIPE_URL, W - 2 * MARGIN - QR_RECIPE_SIZE * 6 - 20),
                    MARGIN, y + 186, GFXFF);

  drawQr(W - MARGIN - 37 * 6, 100, 6);

  apHint(st);
  pageTabs("yours");
#endif
}

static void drawSegmentCard(const CardContent& c, size_t i, int16_t x, int16_t y, int16_t w, int16_t h) {
#ifdef EPAPER_ENABLE
  epaper.drawRoundRect(x, y, w, h, 4, TFT_BLACK);
  int16_t cx = x + 16;
  String label = c.wx_label[i];
  label.toUpperCase();
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(label, cx, y + 12, GFXFF);
  epaper.drawFastHLine(x + 10, y + 34, w - 20, TFT_BLACK);

  epaper.setFreeFont(&FreeSans18pt7b);
  epaper.drawString(c.wx_temp[i], cx, y + 44, GFXFF);
  // Condition icon rides beside the temperature, where the card has room.
  drawWeatherIcon(x + w - 48, y + 42, 30, c.wx_cond[i]);

  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.drawString(c.wx_cond[i], cx, y + 84, GFXFF);

  epaper.setFreeFont(&FreeMono9pt7b);
  String sub = c.wx_wind[i];
  if (c.wx_precip[i].length() > 0) {
    if (sub.length() > 0) sub += "  ";
    sub += c.wx_precip[i];
  }
  epaper.drawString(fit(sub, w - 32), cx, y + h - 22, GFXFF);
#endif
}

static void drawHourStrip(const CardContent& c, int16_t x, int16_t y, int16_t w, int16_t h) {
#ifdef EPAPER_ENABLE
  size_t n = c.wx_hour_count;
  if (n == 0) return;
  const int16_t gap = 2;
  int16_t bar_w = (w - (int16_t)(n - 1) * gap) / (int16_t)n;
  if (bar_w < 3) bar_w = 3;

  uint8_t lo = 255, hi = 0;
  for (size_t i = 0; i < n; i++) {
    if (c.wx_hours[i] < lo) lo = c.wx_hours[i];
    if (c.wx_hours[i] > hi) hi = c.wx_hours[i];
  }
  uint8_t span = hi > lo ? hi - lo : 1;

  for (size_t i = 0; i < n; i++) {
    int16_t bh = 4 + (int16_t)((uint32_t)(c.wx_hours[i] - lo) * (uint32_t)(h - 8) / span);
    int16_t bx = x + (int16_t)i * (bar_w + gap);
    int16_t by = y + h - bh;
    if (i == (size_t)c.wx_hour_now) {
      epaper.fillRect(bx, by, bar_w, bh, TFT_BLACK); // now: solid
    } else {
      epaper.drawRect(bx, by, bar_w, bh, TFT_BLACK);
    }
  }
#endif
}

static void renderWeather(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  header(c, st);

  if (!contentHasWeather(c)) {
    renderEmpty(c, st, "weather", "WEATHER", "No forecast yet", "set up my Dev Day terminal");
    return;
  }

  // Place + date row.
  epaper.setFreeFont(&FreeSans12pt7b);
  const int16_t date_w = epaper.textWidth(c.weather_date, GFXFF);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString(c.weather_date, W - MARGIN, 80, GFXFF);
  epaper.setFreeFont(&FreeSans18pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(fit(c.weather_location, W - 2 * MARGIN - date_w - 24), MARGIN, 74, GFXFF);

  // Hero: current temp + condition icon + condition, hi/lo on the right.
  epaper.setFreeFont(&FreeSansBold24pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(c.weather_now_temp, MARGIN, 116, GFXFF);
  int16_t tw = epaper.textWidth(c.weather_now_temp, GFXFF);
  int16_t cond_x = MARGIN + tw + 20;
  if (wxIconFor(c.weather_now_cond) != WxIcon::NONE) {
    drawWeatherIcon(cond_x, 118, 36, c.weather_now_cond);
    cond_x += 48;
  }
  epaper.setFreeFont(&FreeSans18pt7b);
  epaper.drawString(c.weather_now_cond, cond_x, 124, GFXFF);
  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString(c.weather_now_hilo, W - MARGIN, 128, GFXFF);

  epaper.drawFastHLine(MARGIN, 178, W - 2 * MARGIN, TFT_BLACK);

  // Three day-part cards.
  const int16_t seg_y = 196;
  const int16_t seg_h = 140;
  const int16_t gap = 14;
  const int16_t seg_w = (W - 2 * MARGIN - 2 * gap) / 3;
  size_t n = c.wx_seg_count;
  for (size_t i = 0; i < CardContent::WX_SEGS; i++) {
    int16_t sx = MARGIN + (int16_t)i * (seg_w + gap);
    if (i < n) {
      drawSegmentCard(c, i, sx, seg_y, seg_w, seg_h);
    } else {
      epaper.drawRoundRect(sx, seg_y, seg_w, seg_h, 6, TFT_BLACK);
    }
  }

  // 24-hour temperature skyline. It occupies the same band as the portal
  // credentials, which matter more while the AP is up — drop it entirely then
  // rather than drawing the two on top of each other.
  if (st.ap_hint.length() == 0) {
    epaper.setFreeFont(&FreeSans12pt7b);
    epaper.setTextDatum(TL_DATUM);
    epaper.drawString("Next 24 hours", MARGIN, 346, GFXFF);

    drawHourStrip(c, MARGIN, 372, W - 2 * MARGIN, 36);

    static const char* kHourMarks[4] = {"12a", "6a", "12p", "6p"};
    epaper.setFreeFont(&FreeMono9pt7b);
    const int16_t strip_w = W - 2 * MARGIN;
    for (uint8_t i = 0; i < 4; i++) {
      int16_t hx = MARGIN + (int16_t)i * 6 * strip_w / 24;
      epaper.setTextDatum(i == 0 ? TL_DATUM : TC_DATUM);
      epaper.drawString(kHourMarks[i], hx, 412, GFXFF);
    }
  }

  apHint(st);
  pageTabs("weather");
#endif
}

static bool packedBit(const uint8_t* bits, int16_t w, int16_t x, int16_t y) {
  size_t bit = (size_t)y * (size_t)w + (size_t)x;
  return (bits[bit / 8] & (0x80 >> (bit % 8))) != 0;
}

// The pet (or profile photo) that sits at the top-left of the Usage card.
// Drawn as a plain rectangle: a pet is a whole character, and the circular
// crop the profile photo used would cut off its legs, tail and props. The
// transparent margins baked in by tools/gen_pet.py do the framing instead.
static void drawPet(const CardContent& c, int16_t x0, int16_t y0) {
#ifdef EPAPER_ENABLE
  if (c.dash_avatar_present) {
    for (int16_t y = 0; y < (int16_t)CardContent::PET_H; y++) {
      for (int16_t x = 0; x < (int16_t)CardContent::PET_W; x++) {
        if (packedBit(c.dash_avatar, CardContent::PET_W, x, y)) {
          epaper.drawPixel(x0 + x, y0 + y, TFT_BLACK);
        }
      }
    }
    return;
  }

  // Nothing pushed yet: the pet every unit ships with, so the card is never
  // faceless out of the box.
  for (int16_t y = 0; y < (int16_t)CardContent::PET_H; y++) {
    for (int16_t x = 0; x < (int16_t)CardContent::PET_W; x++) {
      size_t bit = (size_t)y * CardContent::PET_W + (size_t)x;
      uint8_t b = pgm_read_byte(&PET_ASSET_BITMAP[bit / 8]);
      if (b & (0x80 >> (bit % 8))) {
        epaper.drawPixel(x0 + x, y0 + y, TFT_BLACK);
      }
    }
  }
#endif
}

static void drawMetric(int16_t x, int16_t y, int16_t max_w,
                       const String& value, const char* label) {
#ifdef EPAPER_ENABLE
  epaper.setFreeFont(&FreeMonoBold18pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(fit(value.length() ? value : "-", max_w), x, y, GFXFF);
  String up = label;
  up.toUpperCase();
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.drawString(up, x, y + 38, GFXFF);
#endif
}

static void drawDayChart(const CardContent& c, int16_t x, int16_t y, int16_t w, int16_t h) {
#ifdef EPAPER_ENABLE
  epaper.drawRect(x, y, w, h, TFT_BLACK);

  size_t n = c.dash_day_count;
  if (n == 0) {
    epaper.setFreeFont(&FreeSans9pt7b);
    epaper.setTextDatum(MC_DATUM);
    epaper.drawString("Plug in over USB to refresh activity", x + w / 2, y + h / 2, GFXFF);
    return;
  }

  const int16_t pad = 12;
  const int16_t base_y = y + h - pad;          // shared baseline for all bars
  const int16_t inner_w = w - pad * 2;
  const int16_t inner_h = h - pad * 2 - 8;     // leave room for the peak label
  const int16_t gap = 6;
  int16_t bar_w = (inner_w - (int16_t)(n - 1) * gap) / (int16_t)n;
  if (bar_w < 4) bar_w = 4;

  uint8_t peak = 1;
  size_t peak_i = 0;
  for (size_t i = 0; i < n; i++) {
    if (c.dash_day_tokens[i] > peak) {
      peak = c.dash_day_tokens[i];
      peak_i = i;
    }
  }

  // Baseline rule the bars sit on.
  epaper.drawFastHLine(x + pad, base_y, inner_w, TFT_BLACK);

  for (size_t i = 0; i < n; i++) {
    int16_t bh = (int16_t)((uint32_t)c.dash_day_tokens[i] * (uint32_t)inner_h / peak);
    if (c.dash_day_tokens[i] > 0 && bh < 3) bh = 3;
    int16_t bx = x + pad + (int16_t)i * (bar_w + gap);
    int16_t by = base_y - bh;
    if (i == n - 1) {
      // Today: outlined bar with a solid core - reads as "selected".
      epaper.drawRect(bx, by, bar_w, bh, TFT_BLACK);
      if (bh > 6 && bar_w > 6) {
        epaper.fillRect(bx + 3, by + 3, bar_w - 6, bh - 5, TFT_BLACK);
      }
    } else {
      epaper.fillRect(bx, by, bar_w, bh, TFT_BLACK);
    }
    if (i == peak_i && bh > 0) {
      // Tick above the tallest day.
      epaper.fillRect(bx + bar_w / 2 - 1, by - 6, 3, 4, TFT_BLACK);
    }
  }
#endif
}

// First-boot splash: the Build Kit interior card, redrawn at panel scale.
// QR and wordmark up top, and the kit's face — a black dome rising from the
// bottom edge with plus-sign eyes — over the lower half. Pure geometry, so
// there is no bitmap to generate and nothing to alias.
static void renderSplash() {
#ifdef EPAPER_ENABLE
  // The same hardware-recipe QR the Yours page carries, centred like the card.
  const int16_t qr_scale = 3;
  drawQr((W - QR_RECIPE_SIZE * qr_scale) / 2, 36, qr_scale);

  epaper.setTextDatum(MC_DATUM);
  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.drawString("OpenAI DevDay [2026]", W / 2, 184, GFXFF);
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.drawString("Dev Day Terminal", W / 2, 214, GFXFF);

  // The face takes the bottom half of the page: a circle centred on the
  // bottom edge, so exactly its top half shows.
  const int16_t R = H / 2;
  epaper.fillCircle(W / 2, H, R, TFT_BLACK);

  // Plus-sign eyes, measured off the card art: centres half a radius apart
  // (±0.50R), arm-to-stroke ratio 6.3, sitting 58% down the visible dome. The
  // card crops its circle 50px below centre where ours stops at centre, so
  // the vertical numbers scale from the visible dome height, not R.
  const int16_t eye_dx = 120;  // half the distance between eye centres
  const int16_t eye_y = H - R + 135;
  const int16_t arm = 96;      // full width/height of a plus
  const int16_t stroke = 15;
  for (int8_t side = -1; side <= 1; side += 2) {
    const int16_t ex = W / 2 + side * eye_dx;
    epaper.fillRect(ex - arm / 2, eye_y - stroke / 2, arm, stroke, TFT_WHITE);
    epaper.fillRect(ex - stroke / 2, eye_y - arm / 2, stroke, arm, TFT_WHITE);
  }
#endif
}

static void renderDash(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  if (!contentHasDash(c)) {
    renderEmpty(c, st, "dash", "USAGE", "No usage yet", "set up my Dev Day terminal");
    return;
  }
  header(c, st);

  // Top-left anchor, not a centre: the pet is a rectangle, and its baseline
  // wants to sit just above the hairline under the identity block.
  const int16_t pet_x = MARGIN;
  const int16_t pet_y = 52;
  drawPet(c, pet_x, pet_y);

  // Identity runs the full width. Weather lives on its own page (KEY2); a
  // second copy here said nothing the tab strip did not already offer.
  const int16_t text_x = pet_x + (int16_t)CardContent::PET_W + 28;
  const int16_t name_w = W - MARGIN - text_x;

  epaper.setFreeFont(&FreeSansBold24pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(fit(c.dash_name, name_w), text_x, 66, GFXFF);

  epaper.setFreeFont(&FreeSans12pt7b);
  int16_t plan_w = c.dash_plan.length() > 0 ? epaper.textWidth(c.dash_plan, GFXFF) + 32 : 0;
  String handle_line = fit(c.dash_handle, name_w - plan_w);
  epaper.drawString(handle_line, text_x, 118, GFXFF);

  if (c.dash_plan.length() > 0) {
    int16_t hw = epaper.textWidth(handle_line, GFXFF);
    int16_t bx = text_x + hw + 14;
    int16_t by = 112;
    int16_t bw = plan_w - 14;
    int16_t bh = 26;
    epaper.drawRoundRect(bx, by, bw, bh, 4, TFT_BLACK);
    epaper.setTextDatum(ML_DATUM);
    epaper.drawString(c.dash_plan, bx + 9, by + bh / 2, GFXFF);
    epaper.setTextDatum(TL_DATUM);
  }

  // Double hairline — brutalist separation
  epaper.drawFastHLine(MARGIN, 158, W - 2 * MARGIN, TFT_BLACK);
  epaper.drawFastHLine(MARGIN, 160, W - 2 * MARGIN, TFT_BLACK);

  // Today, lifetime total, and current streak — one column per requested metric.
  const int16_t metric_y = 176;
  const int16_t col = (W - 2 * MARGIN) / 3;
  drawMetric(MARGIN + 0 * col, metric_y, col - 12, c.dash_today, "today");
  drawMetric(MARGIN + 1 * col, metric_y, col - 12, c.dash_lifetime, "lifetime");
  drawMetric(MARGIN + 2 * col, metric_y, col - 12, c.dash_streak, "streak");

  epaper.drawFastHLine(MARGIN, 248, W - 2 * MARGIN, TFT_BLACK);
  epaper.drawFastHLine(MARGIN, 250, W - 2 * MARGIN, TFT_BLACK);

  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString("Token activity", MARGIN, 270, GFXFF);
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString("last " + String((unsigned)(c.dash_day_count ? c.dash_day_count : 7)) + " days",
                    W - MARGIN, 274, GFXFF);

  drawDayChart(c, MARGIN, 300, W - 2 * MARGIN, 104);

  // Insight row and the portal credentials share this band; the credentials win.
  if (st.ap_hint.length() == 0) {
    epaper.setFreeFont(&FreeSans9pt7b);
    epaper.setTextDatum(TL_DATUM);
    if (c.dash_insight_left.length()) {
      epaper.drawString(c.dash_insight_left, MARGIN, 412, GFXFF);
    }
    epaper.setTextDatum(TR_DATUM);
    if (c.dash_insight_right.length()) {
      epaper.setFreeFont(&FreeMono9pt7b);
      epaper.drawString(fit(c.dash_insight_right, 260), W - MARGIN, 412, GFXFF);
    } else {
      epaper.setFreeFont(&FreeSans9pt7b);
      epaper.drawString("updates when you plug in", W - MARGIN, 412, GFXFF);
    }
  }

  apHint(st);
  pageTabs("dash");
#endif
}

bool cardIsRenderable(const String& card) {
  return card == "dash" || card == "weather" || card == "agenda" || card == "build" ||
         card == "yours" || card == "splash";
}

bool cardIsStartup(const String& card) {
  return card == "dash" || card == "weather" || card == "agenda" || card == "build" ||
         card == "yours";
}

bool displayBegin() {
#ifdef EPAPER_ENABLE
  epaper.begin();
  epaper.setRotation(0);
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
  return true;
#else
  return false;
#endif
}

void renderCard(const String& card, const CardContent& content, const RenderStatus& status) {
#ifdef EPAPER_ENABLE
  epaper.fillScreen(TFT_WHITE);
  if (card == "splash") renderSplash();
  else if (card == "build") renderBuild(content, status);
  else if (card == "yours") renderYours(content, status);
  else if (card == "weather") renderWeather(content, status);
  else if (card == "agenda") renderAgenda(content, status);
  else renderDash(content, status); // "dash"; every entry point validates first
  epaper.update();
  buttonsNoteDisplayUpdate(); // D3 may share the BUSY line
#endif
}
