#include "cards.h"

#include <SPI.h>
#include <TFT_eSPI.h> // Seeed_GFX (gfxfont.h provides the standard FreeSans fonts)
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

#include "config.h"
#include "buttons.h"
#include "qr_recipe.h"
// Generated by tools/gen_pet.py. Regenerating it changes the bundled pet
// without touching this file.
#include "pet_asset.h"

#ifdef EPAPER_ENABLE
static EPaper epaper = EPaper();
#endif

// 24×24 OpenAI blossom — 1-bit, rasterized from the official openai-blossom.svg
static const uint8_t kBlossom24[72] = {
  0x00, 0x00, 0x00,
  0x00, 0xFC, 0x00,
  0x03, 0x8F, 0xC0,
  0x03, 0x0F, 0xF0,
  0x06, 0x3C, 0x38,
  0x0C, 0x70, 0x18,
  0x3C, 0xC3, 0x8C,
  0x34, 0xCF, 0xEC,
  0x64, 0xFC, 0x7C,
  0x44, 0xFF, 0x1C,
  0x44, 0xC3, 0x8E,
  0x46, 0xC3, 0xE6,
  0x67, 0xC3, 0x62,
  0x71, 0xC3, 0x22,
  0x38, 0xFF, 0x22,
  0x3E, 0x3F, 0x26,
  0x37, 0xF3, 0x2C,
  0x31, 0xC3, 0x3C,
  0x18, 0x0E, 0x30,
  0x1C, 0x3C, 0x60,
  0x0F, 0xF0, 0xC0,
  0x03, 0xF1, 0xC0,
  0x00, 0x3F, 0x00,
  0x00, 0x00, 0x00,
};

static void drawBlossomIcon(int16_t x0, int16_t y0) {
#ifdef EPAPER_ENABLE
  for (int16_t y = 0; y < 24; y++) {
    for (int16_t x = 0; x < 24; x++) {
      size_t bit = (size_t)y * 24 + (size_t)x;
      if (kBlossom24[bit / 8] & (0x80 >> (bit % 8))) {
        epaper.drawPixel(x0 + x, y0 + y, TFT_BLACK);
      }
    }
  }
#endif
}

static constexpr int16_t W = 800;
static constexpr int16_t H = 480;
static constexpr int16_t MARGIN = 28;
static constexpr int16_t DASH_MARGIN = 16;
// Shared exact three-column grid for every terminal page. The 782 px frame
// cannot divide perfectly by three, so the outer cells take the remainder:
// 261 / 260 / 261.
static constexpr int16_t DASH_THIRD_EDGES[4] = {9, 270, 530, 791};

static int16_t drawDashSectionLabel(const String& raw, int16_t x, int16_t y);
static void drawDarkLegend(const String& raw, int16_t x, int16_t y);
static void drawDarkApHint(const RenderStatus& st);
static void pageTabsDark(const char* current);

// Ordered one-bit texture for secondary/history states. Density is deliberately
// limited to two levels: enough to create hierarchy on a monochrome panel,
// without turning small shapes into grey mush after an e-paper refresh.
static void fillDitherRect(int16_t x, int16_t y, int16_t w, int16_t h,
                           uint8_t density, uint16_t color = TFT_BLACK) {
#ifdef EPAPER_ENABLE
  if (w <= 0 || h <= 0 || density == 0) return;
  if (density > 2) density = 2;
  for (int16_t dy = 0; dy < h; dy++) {
    for (int16_t dx = 0; dx < w; dx++) {
      const bool ink = density == 1
                         ? ((dx + dy * 2) & 3) == 0       // 25%
                         : ((dx + dy) & 1) == 0;          // 50%
      if (ink) epaper.drawPixel(x + dx, y + dy, color);
    }
  }
#else
  (void)x; (void)y; (void)w; (void)h; (void)density; (void)color;
#endif
}

static void drawDashedHLine(int16_t x, int16_t y, int16_t w,
                            uint16_t color, int16_t dash = 5,
                            int16_t gap = 3) {
#ifdef EPAPER_ENABLE
  for (int16_t dx = 0; dx < w; dx += dash + gap) {
    const int16_t span = dx + dash <= w ? dash : w - dx;
    epaper.drawFastHLine(x + dx, y, span, color);
  }
#else
  (void)x; (void)y; (void)w; (void)color; (void)dash; (void)gap;
#endif
}

static void drawDashedVLine(int16_t x, int16_t y, int16_t h,
                            uint16_t color, int16_t dash = 5,
                            int16_t gap = 3) {
#ifdef EPAPER_ENABLE
  for (int16_t dy = 0; dy < h; dy += dash + gap) {
    const int16_t span = dy + dash <= h ? dash : h - dy;
    epaper.drawFastVLine(x, y + dy, span, color);
  }
#else
  (void)x; (void)y; (void)h; (void)color; (void)dash; (void)gap;
#endif
}

// Full-width physical-key strip. The three segments line up with the three
// page buttons and never imply touch interaction.
static void pageTabs(const char* current) {
#ifdef EPAPER_ENABLE
  static const char* kIds[3] = {"dash", "weather", "agenda"};
  static const char* kLabels[3] = {"1 USAGE", "2 WEATHER", "3 AGENDA"};
  static const int16_t kWidths[3] = {268, 252, 252};
  int16_t x = 14;
  const int16_t y = 438;
  const int16_t th = 33;
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(MC_DATUM);
  for (uint8_t i = 0; i < 3; i++) {
    const int16_t tw = kWidths[i];
    bool active = current != nullptr && strcmp(current, kIds[i]) == 0;
    if (active) {
      epaper.fillRect(x, y, tw, th, TFT_BLACK);
      epaper.setTextColor(TFT_WHITE, TFT_BLACK);
    } else {
      epaper.drawRect(x, y, tw, th, TFT_BLACK);
      epaper.setTextColor(TFT_BLACK, TFT_WHITE);
    }
    epaper.drawString(kLabels[i], x + tw / 2, y + th / 2 + 1, GFXFF);
    x += tw;
  }
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

// Battery gauge: outline + nub, fill level = charge percent.
static void drawBatteryIcon(int16_t x, int16_t y, uint8_t pct,
                            uint16_t color = TFT_BLACK) {
#ifdef EPAPER_ENABLE
  epaper.drawRect(x, y, 18, 11, color);
  epaper.fillRect(x + 19, y + 3, 2, 5, color); // nub
  if (pct > 100) pct = 100;
  int16_t fill = (int16_t)((uint16_t)pct * 14 / 100);
  if (fill > 0) epaper.fillRect(x + 2, y + 2, fill, 7, color);
#endif
}

// Compact 1-bit Wi-Fi mark. Connected uses stepped arcs; disconnected keeps
// the same silhouette with a separated slash, so state is visible without
// relying on grey or a text label.
static void drawWifiIcon(int16_t x, int16_t y, bool connected,
                         uint16_t color = TFT_BLACK,
                         uint16_t background = TFT_WHITE) {
#ifdef EPAPER_ENABLE
  epaper.fillRect(x + 5, y, 6, 1, color);
  epaper.fillRect(x + 2, y + 1, 3, 1, color);
  epaper.fillRect(x + 11, y + 1, 3, 1, color);
  epaper.fillRect(x + 1, y + 2, 2, 1, color);
  epaper.fillRect(x + 13, y + 2, 2, 1, color);
  epaper.drawPixel(x, y + 3, color);
  epaper.drawPixel(x + 15, y + 3, color);

  epaper.fillRect(x + 6, y + 4, 4, 1, color);
  epaper.fillRect(x + 4, y + 5, 2, 1, color);
  epaper.fillRect(x + 10, y + 5, 2, 1, color);
  epaper.drawPixel(x + 3, y + 6, color);
  epaper.drawPixel(x + 12, y + 6, color);

  epaper.fillRect(x + 7, y + 7, 2, 1, color);
  epaper.drawPixel(x + 6, y + 8, color);
  epaper.drawPixel(x + 9, y + 8, color);
  epaper.fillRect(x + 7, y + 10, 2, 2, color);

  if (!connected) {
    // A 2 px core with a 1 px paper moat remains a slash at arm's length;
    // the old 1 px line broke the tiny arcs into what looked like panel noise.
    // Extend past the glyph so neither endpoint disappears into an arc.
    for (int16_t i = -2; i < 14; i++) {
      epaper.fillRect(x + 1 + i, y + i, 4, 1, background);
    }
    for (int16_t i = -2; i < 14; i++) {
      epaper.fillRect(x + 2 + i, y + i, 2, 1, color);
    }
  }
#endif
}

// ---------------------------------------------------------------------------
// Weather condition icons
//
// Solid silhouettes: at 20-36px on 1-bit e-paper a stroked glyph turns to
// noise, a filled shape stays legible from across a desk. (x, y) is the top
// left of an s-by-s box; the glyph centres itself inside it.
// ---------------------------------------------------------------------------
enum class WxIcon : uint8_t { NONE, SUN, PARTLY, CLOUD, RAIN, SNOW, STORM, FOG };

static WxIcon wxIconFor(const String& cond) {
  String s = cond;
  s.toLowerCase();
  if (s.indexOf("thunder") >= 0 || s.indexOf("storm") >= 0) return WxIcon::STORM;
  if (s.indexOf("snow") >= 0 || s.indexOf("sleet") >= 0) return WxIcon::SNOW;
  if (s.indexOf("rain") >= 0 || s.indexOf("drizzle") >= 0 || s.indexOf("shower") >= 0)
    return WxIcon::RAIN;
  if (s.indexOf("fog") >= 0 || s.indexOf("mist") >= 0 || s.indexOf("haze") >= 0)
    return WxIcon::FOG;
  if (s.indexOf("partly") >= 0 || s.indexOf("mainly") >= 0) return WxIcon::PARTLY;
  if (s.indexOf("cloud") >= 0 || s.indexOf("overcast") >= 0) return WxIcon::CLOUD;
  if (s.indexOf("clear") >= 0 || s.indexOf("sun") >= 0) return WxIcon::SUN;
  return WxIcon::NONE;
}

#ifdef EPAPER_ENABLE
static void wxSunDisc(int16_t cx, int16_t cy, int16_t s, uint16_t color) {
  const int16_t r = s * 22 / 100;
  const int16_t gap = r + s * 6 / 100; // where rays start
  const int16_t len = s * 14 / 100;    // ray length
  const int16_t th = s >= 30 ? 3 : 2;  // ray thickness
  epaper.fillCircle(cx, cy, r, color);
  epaper.fillRect(cx - th / 2, cy - gap - len, th, len, color); // N
  epaper.fillRect(cx - th / 2, cy + gap, th, len, color);       // S
  epaper.fillRect(cx - gap - len, cy - th / 2, len, th, color); // W
  epaper.fillRect(cx + gap, cy - th / 2, len, th, color);       // E
  // Diagonal rays: thickness-sized squares stepped along the 45° line.
  const int16_t d0 = (gap * 100 + 70) / 141;
  const int16_t dn = (len * 100 + 70) / 141;
  for (int16_t k = 0; k < dn; k++) {
    for (int8_t sx = -1; sx <= 1; sx += 2) {
      for (int8_t sy = -1; sy <= 1; sy += 2) {
        epaper.fillRect(cx + sx * (d0 + k) - th / 2, cy + sy * (d0 + k) - th / 2, th, th, color);
      }
    }
  }
}

static void wxCloudShape(int16_t cx, int16_t cy, int16_t s, uint16_t color) {
  // Two lobes over a rounded base; (cx, cy) is the base's centre.
  const int16_t base_w = s * 76 / 100;
  const int16_t base_h = s * 26 / 100;
  epaper.fillCircle(cx - base_w / 2 + base_h / 2 + s * 4 / 100, cy - s * 6 / 100, s * 16 / 100, color);
  epaper.fillCircle(cx + s * 6 / 100, cy - s * 14 / 100, s * 22 / 100, color);
  epaper.fillRoundRect(cx - base_w / 2, cy - base_h / 2, base_w, base_h, base_h / 2, color);
}

static void drawWeatherIcon(int16_t x, int16_t y, int16_t s, const String& cond,
                            uint16_t color = TFT_BLACK,
                            uint16_t background = TFT_WHITE) {
  const WxIcon icon = wxIconFor(cond);
  if (icon == WxIcon::NONE) return;
  const int16_t cx = x + s / 2;
  const int16_t cy = y + s / 2;
  switch (icon) {
    case WxIcon::SUN:
      wxSunDisc(cx, cy, s, color);
      break;
    case WxIcon::PARTLY: {
      // Sun peeking out top-right; an oversized white cloud first, so a
      // margin of paper separates the two shapes.
      wxSunDisc(cx + s * 18 / 100, cy - s * 18 / 100, s * 64 / 100, color);
      const int16_t ccx = cx - s * 4 / 100;
      const int16_t ccy = cy + s * 16 / 100;
      wxCloudShape(ccx, ccy, s * 116 / 100, background);
      wxCloudShape(ccx, ccy, s * 88 / 100, color);
      break;
    }
    case WxIcon::CLOUD:
      wxCloudShape(cx, cy + s * 6 / 100, s, color);
      break;
    case WxIcon::RAIN: {
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, color);
      const int16_t drop = s * 16 / 100 < 4 ? 4 : s * 16 / 100;
      for (int8_t i = 0; i < 3; i++) {
        const int16_t dx = cx - s * 22 / 100 + i * (s * 22 / 100);
        const int16_t dy = cy + s * 10 / 100;
        for (int16_t k = 0; k < drop; k++) {
          epaper.fillRect(dx - k / 2, dy + k, 2, 2, color); // slanted drop
        }
      }
      break;
    }
    case WxIcon::SNOW: {
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, color);
      for (int8_t i = 0; i < 3; i++) {
        const int16_t fx = cx - s * 22 / 100 + i * (s * 22 / 100);
        const int16_t fy = cy + s * 16 / 100 + (i == 1 ? s * 10 / 100 : 0);
        epaper.fillCircle(fx, fy, 2, color);
      }
      break;
    }
    case WxIcon::STORM: {
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, color);
      // Bolt: a staircase of slabs stepping down-left, notched out of the
      // cloud by a white pass so the two shapes never merge into one blob.
      const int16_t bw = s * 18 / 100 < 4 ? 4 : s * 18 / 100;
      const int16_t step = s * 10 / 100 < 3 ? 3 : s * 10 / 100;
      const int16_t bx = cx + s * 2 / 100;
      const int16_t by = cy - s * 2 / 100;
      for (int8_t pass = 0; pass < 2; pass++) {
        const int16_t in = pass == 0 ? 2 : 0;
        const uint16_t pass_color = pass == 0 ? background : color;
        epaper.fillRect(bx - in, by - in, bw + 2 * in, step + 1 + 2 * in, pass_color);
        epaper.fillRect(bx - step / 2 - 1 - in, by + step - in, bw + 2 * in, step + 1 + 2 * in, pass_color);
        epaper.fillRect(bx - step - 2 - in, by + 2 * step - in, bw - 2 + 2 * in, step + 1 + 2 * in, pass_color);
      }
      break;
    }
    case WxIcon::FOG:
      wxCloudShape(cx, cy - s * 12 / 100, s * 84 / 100, color);
      epaper.fillRect(cx - s * 34 / 100, cy + s * 12 / 100, s * 68 / 100, 2, color);
      epaper.fillRect(cx - s * 26 / 100, cy + s * 22 / 100, s * 52 / 100, 2, color);
      break;
    default:
      break;
  }
}
#endif

static void header(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  // Blossom at left; date, Wi-Fi state, battery gauge and percentage at right.
  drawBlossomIcon(MARGIN, 8);
  epaper.setFreeFont(&FreeSans9pt7b);
  const String battery_pct = String(st.battery_pct) + "%";
  const int16_t battery_pct_w = epaper.textWidth(battery_pct, GFXFF);
  const int16_t battery_x = W - MARGIN - battery_pct_w - 4 - 21;
  const int16_t wifi_x = battery_x - 22;
  epaper.setTextDatum(TR_DATUM);
  if (c.header_date.length()) epaper.drawString(c.header_date, wifi_x - 4, 12, GFXFF);
  // Both icons and the percentage share the 9pt text midline.
  drawWifiIcon(wifi_x, 13, st.wifi_connected);
  drawBatteryIcon(battery_x, 13, st.battery_pct);
  epaper.drawString(battery_pct, W - MARGIN, 12, GFXFF);
  // brutalist hairline + 1px double-rule for density
  epaper.drawFastHLine(MARGIN, 42, W - 2 * MARGIN, TFT_BLACK);
  epaper.drawFastHLine(MARGIN, 44, W - 2 * MARGIN, TFT_BLACK);
#endif
}

// Payload strings are attacker-shaped as far as layout is concerned: nothing
// upstream bounds their length, drawString does not clip, and e-paper has no
// scroll. Trim to the space actually available, with an ellipsis so the reader
// can tell something was cut.
static String fit(const String& text, int16_t max_w) {
#ifdef EPAPER_ENABLE
  if (text.length() == 0 || epaper.textWidth(text, GFXFF) <= max_w) return text;
  // Plain ASCII: the GFX free fonts stop at 0x7E, so a U+2026 ellipsis would
  // render as nothing at all on the panel.
  const char* kCut = "...";
  int16_t budget = max_w - epaper.textWidth(kCut, GFXFF);
  if (budget <= 0) return kCut;

  // Longest prefix that fits, stepping only on UTF-8 character boundaries —
  // payloads carry multi-byte glyphs (the ° in every temperature) and half a
  // sequence is not valid text. Lengths here are tens of characters, so a
  // linear walk costs less than the string churn of a binary search.
  size_t n = text.length();
  while (n > 0) {
    while (n > 0 && ((uint8_t)text.charAt(n) & 0xC0) == 0x80) n--; // snap to boundary
    if (epaper.textWidth(text.substring(0, n), GFXFF) <= budget) break;
    n--;
  }
  return text.substring(0, n) + kCut;
#else
  (void)max_w;
  return text;
#endif
}

// The Usage page uses the compact, high-contrast status rail from the selected
// design. Keep the content payload human-readable ("Sunday, August 9") and
// abbreviate only at render time so the other cards can still use the full date.
static String compactDashDate(const String& raw) {
  String value = raw;
  value.trim();
  value.toUpperCase();
  int comma = value.indexOf(",");
  if (comma < 3) return value;

  String weekday = value.substring(0, 3);
  String rest = value.substring(comma + 1, value.length());
  rest.trim();
  int space = rest.indexOf(" ");
  if (space < 0) return weekday + " " + rest;

  String month = rest.substring(0, space);
  if (month.length() > 3) month = month.substring(0, 3);
  String day = rest.substring(space + 1, rest.length());
  day.trim();
  return weekday + " " + month + " " + day;
}

static String compactLastSync(const String& raw) {
  String value = raw;
  value.trim();
  value.toUpperCase();
  if (value.startsWith("LAST SYNC")) return value;

  // dash_sync historically sent "Wed 11:04 PM". Strip the weekday while
  // continuing to accept a bare "11:04 PM" from custom payload producers.
  int colon = value.indexOf(":");
  int space = value.indexOf(" ");
  if (colon >= 0 && space > 0 && space < colon && space <= 3) {
    value = value.substring(space + 1, value.length());
  }
  if (value.length() == 0) value = "--";
  return "LAST SYNC " + value;
}

static void terminalHeader(const char* page, const CardContent& c,
                           const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  const int16_t rail_h = 31;
  epaper.fillRect(0, 0, W, rail_h, TFT_BLACK);
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setTextDatum(TL_DATUM);
  String title = String("DEV DAY / ") + page;
  title.toUpperCase();
  epaper.drawString(title, 18, 6, GFXFF);

  const String battery_pct = String(st.battery_pct) + "%";
  const int16_t pct_right = W - 14;
  const int16_t pct_w = epaper.textWidth(battery_pct, GFXFF);
  const int16_t battery_x = pct_right - pct_w - 5 - 21;
  const int16_t wifi_x = battery_x - 26;
  drawWifiIcon(wifi_x, 8, st.wifi_connected, TFT_WHITE, TFT_BLACK);
  drawBatteryIcon(battery_x, 8, st.battery_pct, TFT_WHITE);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString(battery_pct, pct_right, 6, GFXFF);

  const String sync = compactLastSync(c.dash_insight_right);
  const int16_t sync_right = wifi_x - 12;
  epaper.drawString(sync, sync_right, 6, GFXFF);
  const int16_t date_right = sync_right - epaper.textWidth(sync, GFXFF) - 22;
  const String date = compactDashDate(c.header_date);
  if (date.length()) epaper.drawString(date, date_right, 6, GFXFF);

  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

// Shared inverted command-line rail for the three local terminal pages.
static void terminalHeaderDark(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  epaper.fillRect(0, 0, W, 34, TFT_BLACK);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString("[ DEV DAY 2026 ]", 14, 6, GFXFF);

  const String battery_pct = String(st.battery_pct) + "%";
  const int16_t pct_right = W - 12;
  const int16_t pct_w = epaper.textWidth(battery_pct, GFXFF);
  const int16_t battery_x = pct_right - pct_w - 5 - 21;
  const int16_t wifi_x = battery_x - 26;
  drawWifiIcon(wifi_x, 8, st.wifi_connected, TFT_WHITE, TFT_BLACK);
  drawBatteryIcon(battery_x, 8, st.battery_pct, TFT_WHITE);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString(battery_pct, pct_right, 6, GFXFF);

  const String sync = compactLastSync(c.dash_insight_right);
  const int16_t sync_right = wifi_x - 12;
  epaper.drawString(sync, sync_right, 6, GFXFF);
  const int16_t date_right = sync_right - epaper.textWidth(sync, GFXFF) - 22;
  const String date = compactDashDate(c.header_date);
  if (date.length()) epaper.drawString(date, date_right, 6, GFXFF);

  epaper.drawFastHLine(8, 31, W - 16, TFT_WHITE);
  epaper.drawFastHLine(8, 32, W - 16, TFT_WHITE);
#endif
}

static void apHint(const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  if (st.ap_hint.length() > 0) {
    // Dedicated inverse strip above the physical-key bar. Keeping credentials
    // out of the tab row matters on e-paper because a refresh cannot repair a
    // transient overlap until the next full update.
    epaper.fillRect(MARGIN, 403, W - 2 * MARGIN, 28, TFT_BLACK);
    epaper.setFreeFont(&FreeMono9pt7b);
    epaper.setTextColor(TFT_WHITE, TFT_BLACK);
    epaper.setTextDatum(ML_DATUM);
    epaper.drawString(fit(st.ap_hint, W - 2 * MARGIN - 20), MARGIN + 10, 417, GFXFF);
    epaper.setTextColor(TFT_BLACK, TFT_WHITE);
  }
#endif
}

// Every page that has nothing to show yet says the same thing: what this page
// will be, and the one sentence that makes it real. The tab strip already
// numbers the other pages, so there is nothing else to teach.
static void renderEmpty(const CardContent& c, const RenderStatus& st, const char* tab,
                        const char* label, const char* headline, const char* ask) {
#ifdef EPAPER_ENABLE
  if (strcmp(tab, "dash") == 0 || strcmp(tab, "weather") == 0 ||
      strcmp(tab, "agenda") == 0) {
    terminalHeader(label, c, st);
  } else {
    header(c, st);
  }

  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(label, MARGIN, 86, GFXFF);
  epaper.drawFastHLine(MARGIN, 108, 48, TFT_BLACK);

  epaper.setFreeFont(&FreeSans18pt7b);
  epaper.setTextDatum(MC_DATUM);
  epaper.drawString(headline, W / 2, 204, GFXFF);
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.drawString("Connect over USB and ask Codex:", W / 2, 246, GFXFF);

  // This is a real prompt: the terminal is waiting for exactly this request.
  // Centre the prompt and static e-paper cursor as one unit.
  epaper.setFreeFont(&FreeMono12pt7b);
  const int16_t cursor_gap = 6;
  const int16_t cursor_w = 10;
  const int16_t cursor_h = 18;
  String prompt = fit(String("> ") + ask, W - 2 * MARGIN - cursor_gap - cursor_w);
  const int16_t prompt_w = epaper.textWidth(prompt, GFXFF);
  const int16_t prompt_x = (W - prompt_w - cursor_gap - cursor_w) / 2;
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(prompt, prompt_x, 278, GFXFF);
  epaper.fillRect(prompt_x + prompt_w + cursor_gap, 278 - cursor_h / 2,
                  cursor_w, cursor_h, TFT_BLACK);

  // The splash character waits below the prompt on otherwise empty pages.
  // Portal credentials use this band instead, so they always take priority.
  if (st.ap_hint.length() == 0) {
    const int16_t dome_r = 64;
    const int16_t dome_cx = W / 2;
    const int16_t dome_base = 426;
    epaper.fillCircle(dome_cx, dome_base, dome_r, TFT_BLACK);
    epaper.fillRect(dome_cx - dome_r, dome_base, 2 * dome_r + 1, dome_r + 1, TFT_WHITE);

    const int16_t eye_dx = dome_r / 2;
    const int16_t eye_y = dome_base - dome_r + dome_r * 58 / 100;
    const int16_t arm = 26;
    const int16_t stroke = 4;
    for (int8_t side = -1; side <= 1; side += 2) {
      const int16_t ex = dome_cx + side * eye_dx;
      epaper.fillRect(ex - arm / 2, eye_y - stroke / 2, arm, stroke, TFT_WHITE);
      epaper.fillRect(ex - stroke / 2, eye_y - arm / 2, stroke, arm, TFT_WHITE);
    }
  }

  apHint(st);
  pageTabs(tab);
#endif
}

// Missing local data should not kick a terminal page back into the legacy
// white UI. Keep the same rail, frame, prompt language, and physical-key tabs
// as the populated state so a first sync feels like data arriving in place.
static void renderTerminalEmpty(const CardContent& c, const RenderStatus& st,
                                const char* tab, const char* path,
                                const char* headline, const char* ask) {
#ifdef EPAPER_ENABLE
  epaper.fillScreen(TFT_BLACK);
  terminalHeaderDark(c, st);
  epaper.drawRect(9, 43, 782, 396, TFT_WHITE);
  drawDarkLegend(path, 24, 37);

  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString("STATUS", 24, 64, GFXFF);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString("WAITING FOR LOCAL DATA", 776, 64, GFXFF);
  drawDashedHLine(15, 91, 770, TFT_WHITE);

  epaper.setFreeFont(&FreeMono18pt7b);
  epaper.setTextDatum(MC_DATUM);
  epaper.drawString(headline, W / 2, 180, GFXFF);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.drawString("Connect over USB and ask Codex:", W / 2, 224, GFXFF);

  const int16_t cursor_gap = 6;
  const int16_t cursor_w = 10;
  String prompt = fit(String("> ") + ask, 730 - cursor_gap - cursor_w);
  const int16_t prompt_w = epaper.textWidth(prompt, GFXFF);
  const int16_t prompt_x = (W - prompt_w - cursor_gap - cursor_w) / 2;
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(prompt, prompt_x, 267, GFXFF);
  epaper.fillRect(prompt_x + prompt_w + cursor_gap, 258,
                  cursor_w, 18, TFT_WHITE);

  if (st.ap_hint.length()) {
    drawDarkApHint(st);
  } else {
    drawDashedHLine(15, 404, 770, TFT_WHITE);
    epaper.setTextDatum(MC_DATUM);
    epaper.drawString("USB SYNC  //  LOCAL DATA ONLY", W / 2, 422, GFXFF);
  }
  pageTabsDark(tab);
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#else
  (void)c; (void)st; (void)tab; (void)path; (void)headline; (void)ask;
#endif
}

static void renderBuild(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  epaper.fillScreen(TFT_BLACK);
  terminalHeaderDark(c, st);

  epaper.drawRect(9, 43, 782, 152, TFT_WHITE);
  drawDarkLegend("/sys/firmware", 24, 37);
  drawDashedVLine(DASH_THIRD_EDGES[1], 49, 139, TFT_WHITE);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString("STATUS", 24, 65, GFXFF);
  String state = c.build_state;
  state.toUpperCase();
  epaper.setFreeFont(&FreeMono24pt7b);
  epaper.drawString(fit(state, 230), 24, 96, GFXFF);

  epaper.setFreeFont(&FreeMono18pt7b);
  epaper.drawString(fit(c.build_title, 472), 294, 70, GFXFF);
  epaper.setFreeFont(&FreeSans9pt7b);
  int detail_split = -1;
  for (size_t i = 0; i < c.build_detail.length(); i++) {
    if (c.build_detail.charAt(i) != ' ') continue;
    if (epaper.textWidth(c.build_detail.substring(0, i), GFXFF) <= 472) {
      detail_split = (int)i;
    } else {
      break;
    }
  }
  if (detail_split > 0 &&
      epaper.textWidth(c.build_detail, GFXFF) > 472) {
    epaper.drawString(c.build_detail.substring(0, detail_split), 294, 113, GFXFF);
    epaper.drawString(fit(c.build_detail.substring(detail_split + 1,
                                                    c.build_detail.length()), 472),
                      294, 137, GFXFF);
  } else {
    epaper.drawString(fit(c.build_detail, 472), 294, 124, GFXFF);
  }

  if (c.build_updated_at.length() > 0) {
    epaper.setFreeFont(&FreeMono9pt7b);
    String updated = "UPDATED " + c.build_updated_at;
    updated.toUpperCase();
    epaper.drawString(fit(updated, 472), 294, 168, GFXFF);
  }

  epaper.drawRect(9, 203, 782, 236, TFT_WHITE);
  drawDarkLegend("/dev/hardware", 24, 197);
  drawDashedVLine(DASH_THIRD_EDGES[1], 210, 193, TFT_WHITE);

  String labels[4] = {"FIRMWARE", "BATTERY", "DISPLAY", "LINK"};
  String values[4] = {
    String(FW_NAME " v" FW_VERSION " (") + st.fw_hash + ")",
    String(st.battery_v, 2) + " V (" + String(st.battery_pct) + "%)",
    "UC8179 800x480  //  COMBO 502",
    st.connection,
  };
  const int16_t rows_top = 216;
  const int16_t row_h = 47;
  for (uint8_t i = 0; i < 4; i++) {
    const int16_t row_y = rows_top + (int16_t)i * row_h;
    if (i > 0) drawDashedHLine(15, row_y, 770, TFT_WHITE);
    epaper.setFreeFont(&FreeMonoBold9pt7b);
    epaper.setTextDatum(ML_DATUM);
    epaper.drawString(labels[i], 24, row_y + row_h / 2, GFXFF);
    epaper.setFreeFont(&FreeMono9pt7b);
    epaper.drawString(fit(values[i], 472), 294, row_y + row_h / 2, GFXFF);
  }

  if (st.ap_hint.length()) {
    drawDarkApHint(st);
  } else {
    drawDashedHLine(15, 404, 770, TFT_WHITE);
    epaper.setFreeFont(&FreeMono9pt7b);
    epaper.setTextDatum(MC_DATUM);
    epaper.drawString("FACTORY CHECK  //  USB SERVICE", W / 2, 422, GFXFF);
  }
  pageTabsDark("build");
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

static String formatAgendaTime(const String& raw) {
  String value = raw;
  value.trim();
  if (value.length() == 0) return value;

  // Accept plain times as well as ISO-style date-time values.
  int time_start = 0;
  for (size_t i = 0; i < value.length(); i++) {
    if (value.charAt(i) == 'T' || value.charAt(i) == 't') {
      time_start = (int)i + 1;
    }
  }
  if (time_start > 0 && time_start < (int)value.length()) {
    value = value.substring(time_start, value.length());
  }

  int colon = -1;
  for (size_t i = 0; i < value.length(); i++) {
    if (value.charAt(i) == ':') {
      colon = (int)i;
      break;
    }
  }
  if (colon < 1 || colon + 1 >= (int)value.length()) return raw;

  int hour_start = colon - 1;
  while (hour_start >= 0 && isdigit((unsigned char)value.charAt(hour_start))) hour_start--;
  hour_start++;
  String hour_text = value.substring(hour_start, colon);

  int minute_end = colon + 1;
  while (minute_end < (int)value.length() && isdigit((unsigned char)value.charAt(minute_end))) {
    minute_end++;
  }
  String minute_text = value.substring(colon + 1, minute_end);
  if (hour_text.length() == 0 || minute_text.length() == 0) return raw;

  int hour = atoi(hour_text.c_str());
  int minute = atoi(minute_text.c_str());
  if (minute < 0 || minute > 59) return raw;

  String upper = value;
  upper.toUpperCase();
  bool has_am = false;
  bool has_pm = false;
  for (size_t i = 0; i + 1 < upper.length(); i++) {
    if (upper.charAt(i) == 'A' && upper.charAt(i + 1) == 'M') has_am = true;
    if (upper.charAt(i) == 'P' && upper.charAt(i + 1) == 'M') has_pm = true;
  }

  bool pm = has_pm;
  if (has_am || has_pm) {
    if (hour < 1 || hour > 12) return raw;
  } else {
    if (hour < 0 || hour > 23) return raw;
    pm = hour >= 12;
    hour %= 12;
    if (hour == 0) hour = 12;
  }

  return String(hour) + ":" + (minute < 10 ? "0" : "") + String(minute) + (pm ? " PM" : " AM");
}

static void renderAgenda(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  if (!contentHasAgenda(c)) {
    renderTerminalEmpty(c, st, "agenda", "/var/agenda/today",
                        "No events today", "put my calendar on my terminal");
    return;
  }

  epaper.fillScreen(TFT_BLACK);
  terminalHeaderDark(c, st);
  epaper.drawRect(9, 43, 782, 396, TFT_WHITE);
  drawDarkLegend("/var/agenda/today", 24, 37);

  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(TL_DATUM);
  String adate = c.agenda_date; adate.toUpperCase();
  epaper.drawString(fit(adate, 540), 24, 62, GFXFF);
  epaper.setTextDatum(TR_DATUM);
  String count = String(c.agenda_count) + (c.agenda_count == 1 ? " EVENT" : " EVENTS");
  epaper.drawString(count, 776, 62, GFXFF);
  drawDashedHLine(15, 90, 770, TFT_WHITE);

  const size_t rows =
      c.agenda_count < CardContent::AGENDA_MAX ? c.agenda_count : CardContent::AGENDA_MAX;
  const int16_t rows_top = 96;
  const int16_t rows_bottom = st.ap_hint.length() ? 400 : 431;
  const int16_t row_h = (rows_bottom - rows_top) / (int16_t)rows;
  drawDashedVLine(DASH_THIRD_EDGES[1], rows_top,
                  rows_bottom - rows_top, TFT_WHITE);

  for (size_t i = 0; i < rows; i++) {
    const int16_t ry = rows_top + (int16_t)i * row_h;
    const int16_t center_y = ry + row_h / 2;
    const bool spotlight = rows == 1;
    if (i > 0) drawDashedHLine(15, ry, 770, TFT_WHITE);

    epaper.setFreeFont(&FreeMonoBold9pt7b);
    epaper.setTextDatum(ML_DATUM);
    epaper.drawString(i == 0 ? "> NEXT" : "  QUEUED", 24,
                      center_y - (spotlight ? 42 : 24), GFXFF);

    epaper.setFreeFont(spotlight ? &FreeMono24pt7b : &FreeMono18pt7b);
    epaper.drawString(fit(formatAgendaTime(c.agenda_time[i]), 220), 24,
                      center_y + (spotlight ? 12 : 8), GFXFF);

    const bool has_detail = c.agenda_detail[i].length() > 0;
    epaper.setFreeFont(spotlight ? &FreeSans18pt7b : &FreeSans12pt7b);
    epaper.setTextDatum(has_detail ? BL_DATUM : ML_DATUM);
    epaper.drawString(fit(c.agenda_title[i], 472), 294,
                      has_detail ? center_y - (spotlight ? 4 : 2) : center_y,
                      GFXFF);

    if (has_detail) {
      epaper.setFreeFont(spotlight ? &FreeSans12pt7b : &FreeSans9pt7b);
      epaper.setTextDatum(TL_DATUM);
      epaper.drawString(fit(c.agenda_detail[i], 472), 294,
                        center_y + (spotlight ? 8 : 4), GFXFF);
    }
  }

  if (st.ap_hint.length()) drawDarkApHint(st);
  pageTabsDark("agenda");
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

static void drawQr(int16_t x, int16_t y, uint8_t scale) {
#ifdef EPAPER_ENABLE
  for (uint8_t r = 0; r < QR_RECIPE_SIZE; r++) {
    for (uint8_t col = 0; col < QR_RECIPE_SIZE; col++) {
      uint8_t b = pgm_read_byte(&QR_RECIPE_BITMAP[r][col / 8]);
      if (b & (0x80 >> (col % 8))) {
        epaper.fillRect(x + col * scale, y + r * scale, scale, scale, TFT_BLACK);
      }
    }
  }
#endif
}

static void renderYours(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  epaper.fillScreen(TFT_BLACK);
  terminalHeaderDark(c, st);
  epaper.drawRect(9, 43, 782, 396, TFT_WHITE);
  drawDarkLegend("/dev/terminal", 24, 37);
  drawDashedVLine(DASH_THIRD_EDGES[2], 49, 354, TFT_WHITE);

  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString("OPEN FIRMWARE", 24, 65, GFXFF);
  epaper.setFreeFont(&FreeMono18pt7b);
  epaper.drawString("THIS TERMINAL IS OPEN", 24, 96, GFXFF);
  drawDashedHLine(15, 145, DASH_THIRD_EDGES[2] - 21, TFT_WHITE);

  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.drawString("Flash your own firmware over USB.", 24, 170, GFXFF);
  epaper.drawString("No keys. No locks.", 24, 203, GFXFF);

  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.drawString("SOURCE", 24, 254, GFXFF);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.drawString("github.com/jjeremycai/devday-firmware", 24, 282, GFXFF);

  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.drawString("ASK CODEX", 24, 326, GFXFF);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.drawString("> set up my Dev Day terminal", 24, 354, GFXFF);

  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.setTextDatum(TC_DATUM);
  const int16_t qr_center =
      (DASH_THIRD_EDGES[2] + DASH_THIRD_EDGES[3]) / 2;
  epaper.drawString("SCAN RECIPE", qr_center, 65, GFXFF);
  const int16_t qr_scale = 5;
  const int16_t qr_ink = QR_RECIPE_SIZE * qr_scale;
  const int16_t qr_quiet = 12;
  const int16_t qr_box = qr_ink + 2 * qr_quiet;
  const int16_t qr_box_x = qr_center - qr_box / 2;
  const int16_t qr_box_y = 103;
  epaper.fillRect(qr_box_x, qr_box_y, qr_box, qr_box, TFT_WHITE);
  drawQr(qr_box_x + qr_quiet, qr_box_y + qr_quiet, qr_scale);

  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.drawString("PARTS + WIRING + CODE", qr_center, 337, GFXFF);
  epaper.drawString("README", qr_center, 367, GFXFF);

  if (st.ap_hint.length()) {
    drawDarkApHint(st);
  } else {
    drawDashedHLine(15, 404, 770, TFT_WHITE);
    epaper.setTextDatum(MC_DATUM);
    epaper.drawString("USB FLASH  //  OPEN SOURCE  //  NO LOCKS",
                      W / 2, 422, GFXFF);
  }
  pageTabsDark("yours");
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

static void drawSegmentCard(const CardContent& c, size_t i, int16_t x,
                            int16_t y, int16_t w, int16_t h,
                            uint16_t color = TFT_BLACK,
                            uint16_t background = TFT_WHITE) {
#ifdef EPAPER_ENABLE
  const int16_t cx = x + 16;
  String label = c.wx_label[i];
  label.toUpperCase();
  epaper.setTextColor(color, background);
  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(fit(label, w - 72), cx, y + 10, GFXFF);
  drawWeatherIcon(x + w - 48, y + 7, 30, c.wx_cond[i], color, background);
  drawDashedHLine(x + 16, y + 42, w - 32, color);

  const int16_t reading_y = y + 68;
  epaper.setFreeFont(&FreeMono18pt7b);
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(c.wx_temp[i], cx, reading_y, GFXFF);
  const int16_t temp_w = epaper.textWidth(c.wx_temp[i], GFXFF);

  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.drawString(fit(c.wx_cond[i], w - 44 - temp_w),
                    cx + temp_w + 12, reading_y + 1, GFXFF);

  epaper.setFreeFont(&FreeMonoBold9pt7b);
  String sub = c.wx_wind[i];
  if (c.wx_precip[i].length() > 0) {
    if (sub.length() > 0) sub += "  ";
    sub += c.wx_precip[i];
  }
  epaper.setTextDatum(BL_DATUM);
  epaper.drawString(fit(sub, w - 32), cx, y + h - 10, GFXFF);
#endif
}

static void drawHourStrip(const CardContent& c, int16_t x, int16_t y,
                          int16_t w, int16_t h,
                          uint16_t color = TFT_BLACK,
                          uint16_t background = TFT_WHITE) {
#ifdef EPAPER_ENABLE
  size_t n = c.wx_hour_count;
  if (n == 0) return;
  const int16_t gap = 2;
  int16_t bar_w = (w - (int16_t)(n - 1) * gap) / (int16_t)n;
  if (bar_w < 3) bar_w = 3;

  uint8_t lo = 255, hi = 0;
  for (size_t i = 0; i < n; i++) {
    if (c.wx_hours[i] < lo) lo = c.wx_hours[i];
    if (c.wx_hours[i] > hi) hi = c.wx_hours[i];
  }
  uint8_t span = hi > lo ? hi - lo : 1;

  for (size_t i = 0; i < n; i++) {
    int16_t bh = 4 + (int16_t)((uint32_t)(c.wx_hours[i] - lo) * (uint32_t)(h - 8) / span);
    int16_t bx = x + (int16_t)i * (bar_w + gap);
    int16_t by = y + h - bh;
    if (i == (size_t)c.wx_hour_now) {
      epaper.fillRect(bx, by, bar_w, bh, color); // now: solid
    } else if ((int16_t)i < c.wx_hour_now) {
      epaper.drawRect(bx, by, bar_w, bh, color); // past: textured
      fillDitherRect(bx + 1, by + 1, bar_w - 2, bh - 2, 1, color);
    } else {
      epaper.drawRect(bx, by, bar_w, bh, color); // future: outline
    }
  }
#else
  (void)c; (void)x; (void)y; (void)w; (void)h; (void)color; (void)background;
#endif
}

static void renderWeather(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  if (!contentHasWeather(c)) {
    renderTerminalEmpty(c, st, "weather", "/sys/weather",
                        "No forecast yet", "set up my Dev Day terminal");
    return;
  }

  epaper.fillScreen(TFT_BLACK);
  terminalHeaderDark(c, st);
  epaper.drawRect(9, 43, 782, 127, TFT_WHITE);
  drawDarkLegend("/sys/weather", 24, 37);

  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(fit(c.weather_location, 520), 24, 60, GFXFF);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString(fit(c.weather_date, 220), 776, 60, GFXFF);
  drawDashedHLine(15, 88, 770, TFT_WHITE);

  epaper.setFreeFont(&FreeMono24pt7b);
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(c.weather_now_temp, 24, 128, GFXFF);
  int16_t tw = epaper.textWidth(c.weather_now_temp, GFXFF);
  int16_t cond_x = 24 + tw + 22;
  if (wxIconFor(c.weather_now_cond) != WxIcon::NONE) {
    drawWeatherIcon(cond_x, 103, 48, c.weather_now_cond,
                    TFT_WHITE, TFT_BLACK);
    cond_x += 64;
  }
  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(fit(c.weather_now_cond, 735 - cond_x), cond_x, 128, GFXFF);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(TR_DATUM);
  epaper.drawString(c.weather_now_hilo, 776, 145, GFXFF);

  epaper.drawRect(9, 179, 782, 260, TFT_WHITE);
  drawDarkLegend("/proc/forecast [24h]", 24, 173);
  const int16_t seg_y = 194;
  const int16_t seg_h = 132;
  size_t n = c.wx_seg_count;
  for (size_t i = 0; i < CardContent::WX_SEGS; i++) {
    if (i > 0) {
      drawDashedVLine(DASH_THIRD_EDGES[i], seg_y, seg_h, TFT_WHITE);
    }
    if (i < n) {
      drawSegmentCard(c, i, DASH_THIRD_EDGES[i], seg_y,
                      DASH_THIRD_EDGES[i + 1] - DASH_THIRD_EDGES[i],
                      seg_h, TFT_WHITE, TFT_BLACK);
    }
  }

  drawDashedHLine(15, 333, 770, TFT_WHITE);
  if (st.ap_hint.length() == 0) {
    drawHourStrip(c, 24, 350, 752, 42, TFT_WHITE, TFT_BLACK);

    static const char* kHourMarks[4] = {"12a", "6a", "12p", "6p"};
    epaper.setFreeFont(&FreeMono9pt7b);
    epaper.setTextColor(TFT_WHITE, TFT_BLACK);
    const int16_t strip_w = 752;
    for (uint8_t i = 0; i < 4; i++) {
      int16_t hx = 24 + (int16_t)i * 6 * strip_w / 24;
      epaper.setTextDatum(i == 0 ? TL_DATUM : TC_DATUM);
      epaper.drawString(kHourMarks[i], hx, 405, GFXFF);
    }
  } else {
    drawDarkApHint(st);
  }

  pageTabsDark("weather");
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

static bool packedBit(const uint8_t* bits, int16_t w, int16_t x, int16_t y) {
  size_t bit = (size_t)y * (size_t)w + (size_t)x;
  return (bits[bit / 8] & (0x80 >> (bit % 8))) != 0;
}

// The pet (or profile photo) that sits at the top-left of the Usage card.
// Drawn as a plain rectangle: a pet is a whole character, and the circular
// crop the profile photo used would cut off its legs, tail and props. Nearest-
// neighbour scaling keeps the pushed 1-bit asset crisp at the mock's larger
// profile size without introducing greys or another asset format.
static void drawPet(const CardContent& c, int16_t x0, int16_t y0,
                    int16_t draw_w, int16_t draw_h,
                    bool alternate = false,
                    uint16_t color = TFT_BLACK) {
#ifdef EPAPER_ENABLE
  for (int16_t dy = 0; dy < draw_h; dy++) {
    const int16_t sy = (int16_t)((int32_t)dy * CardContent::PET_H / draw_h);
    for (int16_t dx = 0; dx < draw_w; dx++) {
      const int16_t sx = (int16_t)((int32_t)dx * CardContent::PET_W / draw_w);
      bool ink = false;
      if (c.dash_avatar_present) {
        const uint8_t* bits = alternate && c.dash_avatar_alt_present
                                ? c.dash_avatar_alt : c.dash_avatar;
        ink = packedBit(bits, CardContent::PET_W, sx, sy);
      } else {
        const size_t bit = (size_t)sy * CardContent::PET_W + (size_t)sx;
        const uint8_t* asset = PET_ASSET_BITMAP;
#ifdef PET_ASSET_ALT_PRESENT
        if (alternate) asset = PET_ASSET_ALT_BITMAP;
#endif
        const uint8_t b = pgm_read_byte(&asset[bit / 8]);
        ink = (b & (0x80 >> (bit % 8))) != 0;
      }
      if (ink) {
        epaper.drawPixel(x0 + dx, y0 + dy, color);
      }
    }
  }
#endif
}

static void drawMetric(int16_t x, int16_t y, int16_t max_w,
                       const String& value, const char* label) {
#ifdef EPAPER_ENABLE
  epaper.setFreeFont(&FreeMono18pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(fit(value.length() ? value : "-", max_w), x, y, GFXFF);
  String up = label;
  up.toUpperCase();
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.drawString(up, x, y + 38, GFXFF);
#endif
}

static void drawDayChart(const CardContent& c, int16_t x, int16_t y,
                         int16_t w, int16_t h,
                         uint16_t color = TFT_BLACK) {
#ifdef EPAPER_ENABLE
  size_t n = c.dash_day_count;
  if (n == 0) {
    epaper.setFreeFont(&FreeSans9pt7b);
    epaper.setTextDatum(MC_DATUM);
    epaper.drawString("Plug in over USB to refresh activity", x + w / 2, y + h / 2, GFXFF);
    return;
  }
  if (n > CardContent::DASH_DAYS) n = CardContent::DASH_DAYS;

  const int16_t base_y = y + h - 1;
  const int16_t gap = 11;
  int16_t bar_w = (w - (int16_t)(n - 1) * gap) / (int16_t)n;
  if (bar_w < 4) bar_w = 4;

  uint8_t peak = 1;
  for (size_t i = 0; i < n; i++) {
    if (c.dash_day_tokens[i] > peak) peak = c.dash_day_tokens[i];
  }

  // Baseline rule the bars sit on.
  epaper.drawFastHLine(x, base_y, w, color);

  for (size_t i = 0; i < n; i++) {
    int16_t bh = (int16_t)((uint32_t)c.dash_day_tokens[i] * (uint32_t)(h - 2) / peak);
    if (c.dash_day_tokens[i] > 0 && bh < 3) bh = 3;
    int16_t bx = x + (int16_t)i * (bar_w + gap);
    int16_t by = base_y - bh;
    if (i + 1 == n) {
      epaper.fillRect(bx, by, bar_w, bh, color); // today: solid
    } else {
      const bool current_week = i + 7 >= n;
      epaper.drawRect(bx, by, bar_w, bh, color);
      fillDitherRect(bx + 1, by + 1, bar_w - 2, bh - 2,
                     current_week ? 2 : 1, color);
    }
  }
#endif
}

// First-boot splash: the Build Kit interior card, redrawn at panel scale.
// QR and wordmark up top, and the kit's face — a black dome rising from the
// bottom edge with plus-sign eyes — over the lower half. Pure geometry, so
// there is no bitmap to generate and nothing to alias.
static void renderSplash() {
#ifdef EPAPER_ENABLE
  // The same hardware-recipe QR the Yours page carries, centred like the card.
  const int16_t qr_scale = 3;
  drawQr((W - QR_RECIPE_SIZE * qr_scale) / 2, 36, qr_scale);

  epaper.setTextDatum(MC_DATUM);
  epaper.setFreeFont(&FreeSans12pt7b);
  epaper.drawString("OpenAI DevDay [2026]", W / 2, 184, GFXFF);
  epaper.setFreeFont(&FreeSans9pt7b);
  epaper.drawString("Dev Day Terminal", W / 2, 214, GFXFF);

  // The face takes the bottom half of the page: a circle centred on the
  // bottom edge, so exactly its top half shows.
  const int16_t R = H / 2;
  epaper.fillCircle(W / 2, H, R, TFT_BLACK);

  // Plus-sign eyes, measured off the card art: centres half a radius apart
  // (±0.50R), arm-to-stroke ratio 6.3, sitting 58% down the visible dome. The
  // card crops its circle 50px below centre where ours stops at centre, so
  // the vertical numbers scale from the visible dome height, not R.
  const int16_t eye_dx = 120;  // half the distance between eye centres
  const int16_t eye_y = H - R + 135;
  const int16_t arm = 96;      // full width/height of a plus
  const int16_t stroke = 15;
  for (int8_t side = -1; side <= 1; side += 2) {
    const int16_t ex = W / 2 + side * eye_dx;
    epaper.fillRect(ex - arm / 2, eye_y - stroke / 2, arm, stroke, TFT_WHITE);
    epaper.fillRect(ex - stroke / 2, eye_y - arm / 2, stroke, arm, TFT_WHITE);
  }
#endif
}

static void drawDashMetric(int16_t center_x, const String& value, const char* label) {
#ifdef EPAPER_ENABLE
  epaper.setFreeFont(&FreeSansBold24pt7b);
  epaper.setTextDatum(TC_DATUM);
  epaper.drawString(fit(value.length() ? value : "-", 220), center_x, 198, GFXFF);
  String up = label;
  up.toUpperCase();
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.drawString(up, center_x, 250, GFXFF);
#endif
}

// Keep the whole atlas cell inside the partial-refresh window. A custom frame
// is allowed to use its top row; relying on the bundled pet's transparent
// margin would let those pixels escape the /dev/user frame and never refresh.
static constexpr int16_t DASH_PET_Y = 60;
static constexpr int16_t DASH_PET_H = 165;
// Preserve the 96:104 atlas-cell ratio. The previous 200x185 rectangle made
// every pet about 17% too wide because drawPet scales each axis independently.
static constexpr int16_t DASH_PET_W =
    (DASH_PET_H * CardContent::PET_W + CardContent::PET_H / 2) /
    CardContent::PET_H;
static constexpr int16_t DASH_PET_X =
    DASH_THIRD_EDGES[0] +
    (DASH_THIRD_EDGES[1] - DASH_THIRD_EDGES[0] - DASH_PET_W) / 2;

static void drawDarkLegend(const String& raw, int16_t x, int16_t y) {
#ifdef EPAPER_ENABLE
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  const int16_t w = epaper.textWidth(raw, GFXFF);
  epaper.fillRect(x - 4, y - 2, w + 8, 22, TFT_BLACK);
  epaper.drawString(raw, x, y, GFXFF);
#else
  (void)raw; (void)x; (void)y;
#endif
}

static void drawDarkMetric(int16_t center_x, const String& value,
                           const char* label) {
#ifdef EPAPER_ENABLE
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setTextDatum(TC_DATUM);
  epaper.setFreeFont(&FreeMono9pt7b);
  String up = label;
  up.toUpperCase();
  epaper.drawString(up, center_x, 240, GFXFF);
  epaper.setFreeFont(&FreeMono18pt7b);
  epaper.drawString(fit(value.length() ? value : "-", 220), center_x, 263, GFXFF);
#endif
}

static String legacyDashStat(const String& raw, const char* label) {
  String upper = raw;
  upper.toUpperCase();
  String prefix = String(label) + " ";
  const int start = upper.indexOf(prefix.c_str());
  if (start < 0) return "";
  String value = raw.substring(start + prefix.length(), raw.length());
  const int pipe = value.indexOf("|");
  if (pipe >= 0) value = value.substring(0, pipe);
  value.trim();
  return value;
}

static void drawDarkFooterStat(int16_t x0, int16_t x1,
                               const char* label, const String& value) {
#ifdef EPAPER_ENABLE
  String text = String(label) + " " + (value.length() ? value : "-");
  text.toUpperCase();
  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setTextDatum(MC_DATUM);
  // Six pixels of total breathing room keeps the label/value pair clear of
  // the dashed separators in each one-third cell.
  epaper.drawString(fit(text, x1 - x0 - 6), (x0 + x1) / 2, 422, GFXFF);
#else
  (void)x0; (void)x1; (void)label; (void)value;
#endif
}

static void drawDarkFooter(const CardContent& c) {
#ifdef EPAPER_ENABLE
  String peak = c.dash_peak_day;
  String longest_streak = c.dash_longest_streak;
  if (peak.length() == 0) peak = legacyDashStat(c.dash_insight_left, "PEAK DAY");
  if (longest_streak.length() == 0) {
    longest_streak = legacyDashStat(c.dash_insight_left, "LONGEST STREAK");
  }

  drawDashedHLine(14, 404, 772, TFT_WHITE);
  for (uint8_t i = 1; i < 3; i++) {
    drawDashedVLine(DASH_THIRD_EDGES[i], 410, 24, TFT_WHITE);
  }
  drawDarkFooterStat(DASH_THIRD_EDGES[0], DASH_THIRD_EDGES[1],
                     "PEAK DAY", peak);
  drawDarkFooterStat(DASH_THIRD_EDGES[1], DASH_THIRD_EDGES[2],
                     "LONGEST STREAK", longest_streak);
  drawDarkFooterStat(DASH_THIRD_EDGES[2], DASH_THIRD_EDGES[3],
                     "7D TOTAL", c.dash_seven_day_total);
#endif
}

static void drawDarkApHint(const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  epaper.fillRect(10, 405, 780, 33, TFT_WHITE);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
  epaper.setTextDatum(MC_DATUM);
  epaper.drawString(fit(st.ap_hint, 752), W / 2, 421, GFXFF);
#endif
}

static void pageTabsDark(const char* current) {
#ifdef EPAPER_ENABLE
  static const char* kIds[3] = {"dash", "weather", "agenda"};
  static const char* kLabels[3] = {"1 USAGE", "2 WEATHER", "3 AGENDA"};
  const int16_t y = 448;
  const int16_t h = 30;
  int8_t selected = -1;
  for (uint8_t i = 0; i < 3; i++) {
    if (current != nullptr && strcmp(current, kIds[i]) == 0) selected = (int8_t)i;
  }
  epaper.drawRect(DASH_THIRD_EDGES[0], y,
                  DASH_THIRD_EDGES[3] - DASH_THIRD_EDGES[0], h, TFT_WHITE);
  if (selected >= 0) {
    epaper.fillRect(DASH_THIRD_EDGES[selected] + 1, y + 1,
                    DASH_THIRD_EDGES[selected + 1] - DASH_THIRD_EDGES[selected] - 1,
                    h - 2, TFT_WHITE);
  }
  epaper.drawFastVLine(DASH_THIRD_EDGES[1], y, h, TFT_WHITE);
  epaper.drawFastVLine(DASH_THIRD_EDGES[2], y, h, TFT_WHITE);

  epaper.setFreeFont(&FreeMonoBold9pt7b);
  epaper.setTextDatum(MC_DATUM);
  if (selected >= 0) {
    epaper.setTextColor(TFT_BLACK, TFT_WHITE);
    epaper.drawString(">", DASH_THIRD_EDGES[selected] + 16,
                      y + h / 2 + 1, GFXFF);
  }
  for (uint8_t i = 0; i < 3; i++) {
    const bool active = selected >= 0 && i == (uint8_t)selected;
    epaper.setTextColor(active ? TFT_BLACK : TFT_WHITE,
                        active ? TFT_WHITE : TFT_BLACK);
    epaper.drawString(kLabels[i],
                      (DASH_THIRD_EDGES[i] + DASH_THIRD_EDGES[i + 1]) / 2,
                      y + h / 2 + 1, GFXFF);
  }
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

// Calendar experiment parked at the user's request. Keep the implementation
// nearby for a future revisit, but do not compile or render it in production.
#if 0
static void drawActivityCell(int16_t x, int16_t y, int16_t size, uint8_t level) {
#ifdef EPAPER_ENABLE
  if (level > 4) level = 4;
  epaper.drawRect(x, y, size, size, TFT_BLACK);
  if (level == 0) return;
  if (level == 4) {
    epaper.fillRect(x, y, size, size, TFT_BLACK);
    return;
  }

  // One-bit equivalents of GitHub's intensity shades. Keep a solid outline
  // around every date so zero-activity days still read as a calendar grid.
  for (int16_t dy = 1; dy < size - 1; dy++) {
    for (int16_t dx = 1; dx < size - 1; dx++) {
      bool ink = false;
      if (level == 1) ink = ((dx + dy * 2) % 5) == 0;
      else if (level == 2) ink = ((dx + dy) % 2) == 0;
      else ink = ((dx + dy * 2) % 4) != 0;
      if (ink) epaper.drawPixel(x + dx, y + dy, TFT_BLACK);
    }
  }
#else
  (void)x; (void)y; (void)size; (void)level;
#endif
}

static void drawActivityCalendar(const CardContent& c, int16_t x, int16_t y,
                                 int16_t w, int16_t cell, int16_t row_gap) {
#ifdef EPAPER_ENABLE
  if (c.dash_calendar_count == 0) {
    epaper.setFreeFont(&FreeSans9pt7b);
    epaper.setTextDatum(MC_DATUM);
    epaper.drawString("Sync once to build your local activity calendar",
                      W / 2, y + 36, GFXFF);
    return;
  }

  const size_t count = c.dash_calendar_count < CardContent::DASH_CALENDAR_DAYS
                         ? c.dash_calendar_count : CardContent::DASH_CALENDAR_DAYS;
  static const uint8_t kBandStart[3] = {0, 3, 5};
  static const uint8_t kBandEnd[3] = {3, 5, 7};
  const size_t today_week = c.dash_calendar_today == UINT16_MAX
                              ? CardContent::DASH_CALENDAR_WEEKS
                              : c.dash_calendar_today / 7;
  const uint8_t today_day = c.dash_calendar_today == UINT16_MAX
                              ? 7 : (uint8_t)(c.dash_calendar_today % 7);

  // One column per week, three rows per column. The rows aggregate Sun–Tue,
  // Wed–Thu, and Fri–Sat so a full year stays visible without a seven-row
  // thicket of tiny cells. Columns are distributed across the exact chart
  // width, keeping both activity views edge-aligned.
  for (size_t week = 0; week < CardContent::DASH_CALENDAR_WEEKS; week++) {
    const int16_t cx = x + (int32_t)week * w / CardContent::DASH_CALENDAR_WEEKS;
    for (uint8_t band = 0; band < 3; band++) {
      uint16_t sum = 0;
      uint8_t samples = 0;
      for (uint8_t day = kBandStart[band]; day < kBandEnd[band]; day++) {
        const size_t i = week * 7 + day;
        if (i >= count) continue;
        sum += c.dash_calendar[i];
        samples++;
      }
      const uint8_t level = samples ? (uint8_t)((sum + samples / 2) / samples) : 0;
      const int16_t cy = y + band * (cell + row_gap);
      drawActivityCell(cx, cy, cell, level);
      if (week == today_week && today_day >= kBandStart[band] && today_day < kBandEnd[band]) {
        epaper.drawRect(cx - 1, cy - 1, cell + 2, cell + 2, TFT_BLACK);
      }
    }
  }
#else
  (void)c; (void)x; (void)y; (void)w; (void)cell; (void)row_gap;
#endif
}
#endif

static int16_t drawDashSectionLabel(const String& raw, int16_t x, int16_t y) {
#ifdef EPAPER_ENABLE
  String label = raw;
  label.toUpperCase();
  epaper.setFreeFont(&FreeMono9pt7b);
  const int16_t w = epaper.textWidth(label, GFXFF) + 24;
  const int16_t h = 25;
  epaper.fillRect(x, y, w, h, TFT_BLACK);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setTextDatum(MC_DATUM);
  epaper.drawString(label, x + w / 2, y + h / 2 + 1, GFXFF);
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
  return w;
#else
  (void)raw; (void)x; (void)y;
  return 0;
#endif
}

static void drawDashSummary(const String& raw) {
#ifdef EPAPER_ENABLE
  String left = raw;
  String right;
  const int split = left.indexOf("|");
  if (split >= 0) {
    right = left.substring(split + 1, left.length());
    left = left.substring(0, split);
  }
  left.trim();
  right.trim();
  left.toUpperCase();
  right.toUpperCase();

  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextDatum(TL_DATUM);
  left = fit(left, right.length() ? 265 : W - 2 * DASH_MARGIN);
  epaper.drawString(left, 22, 405, GFXFF);
  if (right.length()) {
    const int16_t left_w = epaper.textWidth(left, GFXFF);
    const int16_t bullet_x = 22 + left_w + 16;
    epaper.fillCircle(bullet_x, 414, 2, TFT_BLACK);
    epaper.drawString(fit(right, W - bullet_x - 30), bullet_x + 16, 405, GFXFF);
  }
#endif
}

static void drawDashApHint(const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  epaper.fillRect(DASH_MARGIN, 402, W - 2 * DASH_MARGIN, 29, TFT_BLACK);
  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(fit(st.ap_hint, W - 2 * DASH_MARGIN - 20),
                    DASH_MARGIN + 10, 416, GFXFF);
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

// Parked calendar layout. It remains here, disabled, so the experiment can be
// recovered without asking the sync bridge to invent or refetch any data.
#if 0
static void renderDashWithCalendar(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  if (!contentHasDash(c)) {
    renderEmpty(c, st, "dash", "USAGE", "No usage yet", "set up my Dev Day terminal");
    return;
  }
  terminalHeader("USAGE", c, st);

  // Identity and local metrics share one compact badge-like band, leaving
  // enough vertical room for both the short-term chart and year calendar.
  const int16_t pet_x = 14;
  const int16_t pet_y = 33;
  drawPet(c, pet_x, pet_y, 96, 104);
  epaper.drawFastVLine(121, 40, 96, TFT_BLACK);

  const int16_t text_x = 139;
  const int16_t name_w = 226;

  epaper.setFreeFont(&FreeSansBold18pt7b);
  epaper.setTextDatum(TL_DATUM);
  epaper.drawString(fit(c.dash_name, name_w), text_x, 44, GFXFF);

  epaper.setFreeFont(&FreeSans9pt7b);
  String plan = c.dash_plan;
  plan.toUpperCase();
  String handle_line = fit(c.dash_handle, name_w);
  epaper.drawString(handle_line, text_x, 83, GFXFF);

  if (plan.length() > 0) {
    epaper.setFreeFont(&FreeMono9pt7b);
    int16_t bx = text_x;
    int16_t by = 107;
    int16_t bw = epaper.textWidth(plan, GFXFF) + 16;
    int16_t bh = 25;
    epaper.drawRoundRect(bx, by, bw, bh, 2, TFT_BLACK);
    epaper.setTextDatum(ML_DATUM);
    epaper.drawString(plan, bx + 10, by + bh / 2, GFXFF);
    epaper.setTextDatum(TL_DATUM);
  }

  epaper.drawFastVLine(378, 40, 96, TFT_BLACK);
  drawDashMetric(444, 47, c.dash_today, "today");
  drawDashMetric(574, 47, c.dash_lifetime, "lifetime");
  drawDashMetric(708, 47, c.dash_streak, "streak");
  epaper.drawFastVLine(508, 48, 71, TFT_BLACK);
  epaper.drawFastVLine(640, 48, 71, TFT_BLACK);

  const int16_t label_y = 146;
  const int16_t left_x = 18;
  epaper.setFreeFont(&FreeMono9pt7b);
  const String range = String((unsigned)(c.dash_day_count ? c.dash_day_count : 14)) + " DAYS";
  const int16_t right_w = epaper.textWidth(range, GFXFF) + 24;
  const int16_t right_x = W - 18 - right_w;
  const int16_t left_w = epaper.textWidth("TOKEN ACTIVITY", GFXFF) + 24;
  epaper.drawFastHLine(left_x + left_w, label_y + 12,
                      right_x - (left_x + left_w), TFT_BLACK);
  drawDashSectionLabel("TOKEN ACTIVITY", left_x, label_y);
  drawDashSectionLabel(range, right_x, label_y);

  drawDayChart(c, 22, 178, W - 44, 68);

  const int16_t calendar_label_y = 255;
  const String calendar_range = "LAST YEAR";
  epaper.setFreeFont(&FreeMono9pt7b);
  const int16_t calendar_right_w = epaper.textWidth(calendar_range, GFXFF) + 24;
  const int16_t calendar_right_x = W - 18 - calendar_right_w;
  const int16_t calendar_left_w = epaper.textWidth("ACTIVITY CALENDAR", GFXFF) + 24;
  epaper.drawFastHLine(left_x + calendar_left_w, calendar_label_y + 12,
                      calendar_right_x - (left_x + calendar_left_w), TFT_BLACK);
  drawDashSectionLabel("ACTIVITY CALENDAR", left_x, calendar_label_y);
  drawDashSectionLabel(calendar_range, calendar_right_x, calendar_label_y);

  drawActivityCalendar(c, 22, 288, W - 44, 13, 6);

  // Portal credentials replace the summary band so neither can overlap the
  // physical-key strip on the slow-refresh display.
  if (st.ap_hint.length()) {
    drawDashApHint(st);
  } else if (c.dash_insight_left.length()) {
    drawDashSummary(c.dash_insight_left);
  }

  pageTabs("dash");
#endif
}
#endif

static void renderDash(const CardContent& c, const RenderStatus& st) {
#ifdef EPAPER_ENABLE
  if (!contentHasDash(c)) {
    renderTerminalEmpty(c, st, "dash", "/proc/token_activity",
                        "No usage yet", "set up my Dev Day terminal");
    return;
  }
  epaper.fillScreen(TFT_BLACK);
  terminalHeaderDark(c, st);

  // /dev/user: profile and top-line metrics share one framed command block.
  epaper.drawRect(9, 43, 782, 271, TFT_WHITE);
  drawDarkLegend("/dev/user", 24, 37);
  drawPet(c, DASH_PET_X, DASH_PET_Y, DASH_PET_W, DASH_PET_H,
          false, TFT_WHITE);
  drawDashedVLine(DASH_THIRD_EDGES[1], 49, 176, TFT_WHITE);

  const int16_t text_x = 329;
  const int16_t name_w = 432;
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  epaper.setTextDatum(TL_DATUM);
  epaper.setFreeFont(&FreeMono24pt7b);
  epaper.drawString(fit(c.dash_name, name_w), text_x, 69, GFXFF);

  epaper.setFreeFont(&FreeMono9pt7b);
  epaper.drawString(fit(c.dash_handle, name_w), text_x, 130, GFXFF);

  String plan = c.dash_plan;
  plan.toUpperCase();
  if (plan.length() > 0) {
    epaper.setFreeFont(&FreeMono9pt7b);
    const int16_t bx = text_x;
    const int16_t by = 164;
    int16_t bw = epaper.textWidth(plan, GFXFF) + 16;
    const int16_t bh = 27;
    epaper.drawRect(bx, by, bw, bh, TFT_WHITE);
    epaper.setTextDatum(MC_DATUM);
    epaper.drawString(plan, bx + bw / 2, by + bh / 2 + 1, GFXFF);
  }

  drawDashedHLine(14, 230, 772, TFT_WHITE);
  drawDashedVLine(DASH_THIRD_EDGES[1], 236, 71, TFT_WHITE);
  drawDashedVLine(DASH_THIRD_EDGES[2], 236, 71, TFT_WHITE);
  drawDarkMetric((DASH_THIRD_EDGES[0] + DASH_THIRD_EDGES[1]) / 2,
                 c.dash_today, "today");
  drawDarkMetric((DASH_THIRD_EDGES[1] + DASH_THIRD_EDGES[2]) / 2,
                 c.dash_lifetime, "lifetime");
  drawDarkMetric((DASH_THIRD_EDGES[2] + DASH_THIRD_EDGES[3]) / 2,
                 c.dash_streak, "current streak");

  // /proc/token_activity: 14 normalized daily bars over the real three-cell
  // local summary. Previous/current week use ordered dither; today is solid.
  epaper.drawRect(9, 322, 782, 117, TFT_WHITE);
  drawDarkLegend("/proc/token_activity [14d]", 24, 316);
  epaper.setTextColor(TFT_WHITE, TFT_BLACK);
  drawDayChart(c, 24, 333, 752, 62, TFT_WHITE);

  if (st.ap_hint.length()) {
    drawDarkApHint(st);
  } else {
    drawDarkFooter(c);
  }

  pageTabsDark("dash");
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
#endif
}

bool dashPetCanAnimate(const CardContent& c) {
  if (!contentHasDash(c)) return false;
  if (c.dash_avatar_present) {
    return c.dash_avatar_alt_present &&
           memcmp(c.dash_avatar, c.dash_avatar_alt, CardContent::PET_BYTES) != 0;
  }
#ifdef PET_ASSET_ALT_PRESENT
  for (size_t i = 0; i < CardContent::PET_BYTES; i++) {
    if (pgm_read_byte(&PET_ASSET_BITMAP[i]) !=
        pgm_read_byte(&PET_ASSET_ALT_BITMAP[i])) return true;
  }
  return false;
#else
  return false;
#endif
}

void renderDashPetFrame(const CardContent& c, bool alternate) {
#ifdef EPAPER_ENABLE
  if (!dashPetCanAnimate(c)) return;
  // Keep the partial window inside /dev/user so it cannot disturb the frame,
  // label, or one-third divider. updataPartial() aligns the x range for the
  // controller and uses the UC8179 partial waveform.
  static constexpr int16_t partial_y = DASH_PET_Y;
  static constexpr int16_t partial_h = DASH_PET_H;
  epaper.fillRect(DASH_PET_X, partial_y, DASH_PET_W, partial_h, TFT_BLACK);
  drawPet(c, DASH_PET_X, DASH_PET_Y, DASH_PET_W, DASH_PET_H,
          alternate, TFT_WHITE);
  epaper.updataPartial(DASH_PET_X, partial_y, DASH_PET_W, partial_h);
  buttonsNoteDisplayUpdate();
#else
  (void)c; (void)alternate;
#endif
}

bool cardIsRenderable(const String& card) {
  return card == "dash" || card == "weather" || card == "agenda" || card == "build" ||
         card == "yours" || card == "splash";
}

bool cardIsStartup(const String& card) {
  return card == "dash" || card == "weather" || card == "agenda" || card == "build" ||
         card == "yours";
}

bool displayBegin() {
#ifdef EPAPER_ENABLE
  epaper.begin();
  epaper.setRotation(0);
  epaper.setTextColor(TFT_BLACK, TFT_WHITE);
  return true;
#else
  return false;
#endif
}

void renderCard(const String& card, const CardContent& content, const RenderStatus& status) {
#ifdef EPAPER_ENABLE
  epaper.fillScreen(TFT_WHITE);
  if (card == "splash") renderSplash();
  else if (card == "build") renderBuild(content, status);
  else if (card == "yours") renderYours(content, status);
  else if (card == "weather") renderWeather(content, status);
  else if (card == "agenda") renderAgenda(content, status);
  else renderDash(content, status); // "dash"; every entry point validates first
  epaper.update();
  buttonsNoteDisplayUpdate(); // D3 may share the BUSY line
#endif
}
